package com.geeker.marketing.dao.micro.generator.model;

import java.io.Serializable;
import java.util.Date;

public class OpDeviceCmd implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column op_device_cmd.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column op_device_cmd.com_id
     *
     * @mbg.generated
     */
    private Integer comId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column op_device_cmd.user_id
     *
     * @mbg.generated
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column op_device_cmd.device_id
     *
     * @mbg.generated
     */
    private String deviceId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column op_device_cmd.cmd_type_cd
     *
     * @mbg.generated
     */
    private String cmdTypeCd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column op_device_cmd.cmd_cd
     *
     * @mbg.generated
     */
    private String cmdCd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column op_device_cmd.cmd_parm
     *
     * @mbg.generated
     */
    private String cmdParm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column op_device_cmd.deliver_time
     *
     * @mbg.generated
     */
    private Date deliverTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column op_device_cmd.deliver_status
     *
     * @mbg.generated
     */
    private Integer deliverStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column op_device_cmd.receive_result
     *
     * @mbg.generated
     */
    private String receiveResult;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column op_device_cmd.receive_time
     *
     * @mbg.generated
     */
    private Date receiveTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column op_device_cmd.receive_status
     *
     * @mbg.generated
     */
    private Integer receiveStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column op_device_cmd.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column op_device_cmd.queue
     *
     * @mbg.generated
     */
    private String queue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column op_device_cmd.queue_msg_id
     *
     * @mbg.generated
     */
    private String queueMsgId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column op_device_cmd.queue_time
     *
     * @mbg.generated
     */
    private Date queueTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table op_device_cmd
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column op_device_cmd.id
     *
     * @return the value of op_device_cmd.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column op_device_cmd.id
     *
     * @param id the value for op_device_cmd.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column op_device_cmd.com_id
     *
     * @return the value of op_device_cmd.com_id
     *
     * @mbg.generated
     */
    public Integer getComId() {
        return comId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column op_device_cmd.com_id
     *
     * @param comId the value for op_device_cmd.com_id
     *
     * @mbg.generated
     */
    public void setComId(Integer comId) {
        this.comId = comId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column op_device_cmd.user_id
     *
     * @return the value of op_device_cmd.user_id
     *
     * @mbg.generated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column op_device_cmd.user_id
     *
     * @param userId the value for op_device_cmd.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column op_device_cmd.device_id
     *
     * @return the value of op_device_cmd.device_id
     *
     * @mbg.generated
     */
    public String getDeviceId() {
        return deviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column op_device_cmd.device_id
     *
     * @param deviceId the value for op_device_cmd.device_id
     *
     * @mbg.generated
     */
    public void setDeviceId(String deviceId) {
        this.deviceId = deviceId == null ? null : deviceId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column op_device_cmd.cmd_type_cd
     *
     * @return the value of op_device_cmd.cmd_type_cd
     *
     * @mbg.generated
     */
    public String getCmdTypeCd() {
        return cmdTypeCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column op_device_cmd.cmd_type_cd
     *
     * @param cmdTypeCd the value for op_device_cmd.cmd_type_cd
     *
     * @mbg.generated
     */
    public void setCmdTypeCd(String cmdTypeCd) {
        this.cmdTypeCd = cmdTypeCd == null ? null : cmdTypeCd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column op_device_cmd.cmd_cd
     *
     * @return the value of op_device_cmd.cmd_cd
     *
     * @mbg.generated
     */
    public String getCmdCd() {
        return cmdCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column op_device_cmd.cmd_cd
     *
     * @param cmdCd the value for op_device_cmd.cmd_cd
     *
     * @mbg.generated
     */
    public void setCmdCd(String cmdCd) {
        this.cmdCd = cmdCd == null ? null : cmdCd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column op_device_cmd.cmd_parm
     *
     * @return the value of op_device_cmd.cmd_parm
     *
     * @mbg.generated
     */
    public String getCmdParm() {
        return cmdParm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column op_device_cmd.cmd_parm
     *
     * @param cmdParm the value for op_device_cmd.cmd_parm
     *
     * @mbg.generated
     */
    public void setCmdParm(String cmdParm) {
        this.cmdParm = cmdParm == null ? null : cmdParm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column op_device_cmd.deliver_time
     *
     * @return the value of op_device_cmd.deliver_time
     *
     * @mbg.generated
     */
    public Date getDeliverTime() {
        return deliverTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column op_device_cmd.deliver_time
     *
     * @param deliverTime the value for op_device_cmd.deliver_time
     *
     * @mbg.generated
     */
    public void setDeliverTime(Date deliverTime) {
        this.deliverTime = deliverTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column op_device_cmd.deliver_status
     *
     * @return the value of op_device_cmd.deliver_status
     *
     * @mbg.generated
     */
    public Integer getDeliverStatus() {
        return deliverStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column op_device_cmd.deliver_status
     *
     * @param deliverStatus the value for op_device_cmd.deliver_status
     *
     * @mbg.generated
     */
    public void setDeliverStatus(Integer deliverStatus) {
        this.deliverStatus = deliverStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column op_device_cmd.receive_result
     *
     * @return the value of op_device_cmd.receive_result
     *
     * @mbg.generated
     */
    public String getReceiveResult() {
        return receiveResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column op_device_cmd.receive_result
     *
     * @param receiveResult the value for op_device_cmd.receive_result
     *
     * @mbg.generated
     */
    public void setReceiveResult(String receiveResult) {
        this.receiveResult = receiveResult == null ? null : receiveResult.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column op_device_cmd.receive_time
     *
     * @return the value of op_device_cmd.receive_time
     *
     * @mbg.generated
     */
    public Date getReceiveTime() {
        return receiveTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column op_device_cmd.receive_time
     *
     * @param receiveTime the value for op_device_cmd.receive_time
     *
     * @mbg.generated
     */
    public void setReceiveTime(Date receiveTime) {
        this.receiveTime = receiveTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column op_device_cmd.receive_status
     *
     * @return the value of op_device_cmd.receive_status
     *
     * @mbg.generated
     */
    public Integer getReceiveStatus() {
        return receiveStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column op_device_cmd.receive_status
     *
     * @param receiveStatus the value for op_device_cmd.receive_status
     *
     * @mbg.generated
     */
    public void setReceiveStatus(Integer receiveStatus) {
        this.receiveStatus = receiveStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column op_device_cmd.create_time
     *
     * @return the value of op_device_cmd.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column op_device_cmd.create_time
     *
     * @param createTime the value for op_device_cmd.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column op_device_cmd.queue
     *
     * @return the value of op_device_cmd.queue
     *
     * @mbg.generated
     */
    public String getQueue() {
        return queue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column op_device_cmd.queue
     *
     * @param queue the value for op_device_cmd.queue
     *
     * @mbg.generated
     */
    public void setQueue(String queue) {
        this.queue = queue == null ? null : queue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column op_device_cmd.queue_msg_id
     *
     * @return the value of op_device_cmd.queue_msg_id
     *
     * @mbg.generated
     */
    public String getQueueMsgId() {
        return queueMsgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column op_device_cmd.queue_msg_id
     *
     * @param queueMsgId the value for op_device_cmd.queue_msg_id
     *
     * @mbg.generated
     */
    public void setQueueMsgId(String queueMsgId) {
        this.queueMsgId = queueMsgId == null ? null : queueMsgId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column op_device_cmd.queue_time
     *
     * @return the value of op_device_cmd.queue_time
     *
     * @mbg.generated
     */
    public Date getQueueTime() {
        return queueTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column op_device_cmd.queue_time
     *
     * @param queueTime the value for op_device_cmd.queue_time
     *
     * @mbg.generated
     */
    public void setQueueTime(Date queueTime) {
        this.queueTime = queueTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table op_device_cmd
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", comId=").append(comId);
        sb.append(", userId=").append(userId);
        sb.append(", deviceId=").append(deviceId);
        sb.append(", cmdTypeCd=").append(cmdTypeCd);
        sb.append(", cmdCd=").append(cmdCd);
        sb.append(", cmdParm=").append(cmdParm);
        sb.append(", deliverTime=").append(deliverTime);
        sb.append(", deliverStatus=").append(deliverStatus);
        sb.append(", receiveResult=").append(receiveResult);
        sb.append(", receiveTime=").append(receiveTime);
        sb.append(", receiveStatus=").append(receiveStatus);
        sb.append(", createTime=").append(createTime);
        sb.append(", queue=").append(queue);
        sb.append(", queueMsgId=").append(queueMsgId);
        sb.append(", queueTime=").append(queueTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}