package com.geeker.marketing.dao.micro.generator.model;

import java.io.Serializable;
import java.util.Date;

public class OpDeviceReport implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column op_device_report.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column op_device_report.com_id
     *
     * @mbg.generated
     */
    private Integer comId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column op_device_report.device_id
     *
     * @mbg.generated
     */
    private String deviceId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column op_device_report.cmd_type_cd
     *
     * @mbg.generated
     */
    private String cmdTypeCd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column op_device_report.cmd_cd
     *
     * @mbg.generated
     */
    private String cmdCd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column op_device_report.receive_result
     *
     * @mbg.generated
     */
    private String receiveResult;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column op_device_report.receive_time
     *
     * @mbg.generated
     */
    private Date receiveTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column op_device_report.receive_status
     *
     * @mbg.generated
     */
    private Boolean receiveStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column op_device_report.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column op_device_report.queue
     *
     * @mbg.generated
     */
    private String queue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column op_device_report.message_id
     *
     * @mbg.generated
     */
    private String messageId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column op_device_report.queue_time
     *
     * @mbg.generated
     */
    private Date queueTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table op_device_report
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column op_device_report.id
     *
     * @return the value of op_device_report.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column op_device_report.id
     *
     * @param id the value for op_device_report.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column op_device_report.com_id
     *
     * @return the value of op_device_report.com_id
     *
     * @mbg.generated
     */
    public Integer getComId() {
        return comId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column op_device_report.com_id
     *
     * @param comId the value for op_device_report.com_id
     *
     * @mbg.generated
     */
    public void setComId(Integer comId) {
        this.comId = comId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column op_device_report.device_id
     *
     * @return the value of op_device_report.device_id
     *
     * @mbg.generated
     */
    public String getDeviceId() {
        return deviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column op_device_report.device_id
     *
     * @param deviceId the value for op_device_report.device_id
     *
     * @mbg.generated
     */
    public void setDeviceId(String deviceId) {
        this.deviceId = deviceId == null ? null : deviceId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column op_device_report.cmd_type_cd
     *
     * @return the value of op_device_report.cmd_type_cd
     *
     * @mbg.generated
     */
    public String getCmdTypeCd() {
        return cmdTypeCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column op_device_report.cmd_type_cd
     *
     * @param cmdTypeCd the value for op_device_report.cmd_type_cd
     *
     * @mbg.generated
     */
    public void setCmdTypeCd(String cmdTypeCd) {
        this.cmdTypeCd = cmdTypeCd == null ? null : cmdTypeCd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column op_device_report.cmd_cd
     *
     * @return the value of op_device_report.cmd_cd
     *
     * @mbg.generated
     */
    public String getCmdCd() {
        return cmdCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column op_device_report.cmd_cd
     *
     * @param cmdCd the value for op_device_report.cmd_cd
     *
     * @mbg.generated
     */
    public void setCmdCd(String cmdCd) {
        this.cmdCd = cmdCd == null ? null : cmdCd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column op_device_report.receive_result
     *
     * @return the value of op_device_report.receive_result
     *
     * @mbg.generated
     */
    public String getReceiveResult() {
        return receiveResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column op_device_report.receive_result
     *
     * @param receiveResult the value for op_device_report.receive_result
     *
     * @mbg.generated
     */
    public void setReceiveResult(String receiveResult) {
        this.receiveResult = receiveResult == null ? null : receiveResult.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column op_device_report.receive_time
     *
     * @return the value of op_device_report.receive_time
     *
     * @mbg.generated
     */
    public Date getReceiveTime() {
        return receiveTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column op_device_report.receive_time
     *
     * @param receiveTime the value for op_device_report.receive_time
     *
     * @mbg.generated
     */
    public void setReceiveTime(Date receiveTime) {
        this.receiveTime = receiveTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column op_device_report.receive_status
     *
     * @return the value of op_device_report.receive_status
     *
     * @mbg.generated
     */
    public Boolean getReceiveStatus() {
        return receiveStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column op_device_report.receive_status
     *
     * @param receiveStatus the value for op_device_report.receive_status
     *
     * @mbg.generated
     */
    public void setReceiveStatus(Boolean receiveStatus) {
        this.receiveStatus = receiveStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column op_device_report.create_time
     *
     * @return the value of op_device_report.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column op_device_report.create_time
     *
     * @param createTime the value for op_device_report.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column op_device_report.queue
     *
     * @return the value of op_device_report.queue
     *
     * @mbg.generated
     */
    public String getQueue() {
        return queue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column op_device_report.queue
     *
     * @param queue the value for op_device_report.queue
     *
     * @mbg.generated
     */
    public void setQueue(String queue) {
        this.queue = queue == null ? null : queue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column op_device_report.message_id
     *
     * @return the value of op_device_report.message_id
     *
     * @mbg.generated
     */
    public String getMessageId() {
        return messageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column op_device_report.message_id
     *
     * @param messageId the value for op_device_report.message_id
     *
     * @mbg.generated
     */
    public void setMessageId(String messageId) {
        this.messageId = messageId == null ? null : messageId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column op_device_report.queue_time
     *
     * @return the value of op_device_report.queue_time
     *
     * @mbg.generated
     */
    public Date getQueueTime() {
        return queueTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column op_device_report.queue_time
     *
     * @param queueTime the value for op_device_report.queue_time
     *
     * @mbg.generated
     */
    public void setQueueTime(Date queueTime) {
        this.queueTime = queueTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table op_device_report
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", comId=").append(comId);
        sb.append(", deviceId=").append(deviceId);
        sb.append(", cmdTypeCd=").append(cmdTypeCd);
        sb.append(", cmdCd=").append(cmdCd);
        sb.append(", receiveResult=").append(receiveResult);
        sb.append(", receiveTime=").append(receiveTime);
        sb.append(", receiveStatus=").append(receiveStatus);
        sb.append(", createTime=").append(createTime);
        sb.append(", queue=").append(queue);
        sb.append(", messageId=").append(messageId);
        sb.append(", queueTime=").append(queueTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}