package com.geeker.marketing.dao.micro.generator.model;

import java.io.Serializable;
import java.util.Date;

public class SysErrorProcLog implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_error_proc_log.proc_name
     *
     * @mbg.generated
     */
    private String procName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_error_proc_log.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_error_proc_log.object_id
     *
     * @mbg.generated
     */
    private String objectId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_error_proc_log.object_type
     *
     * @mbg.generated
     */
    private String objectType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_error_proc_log.sql_process
     *
     * @mbg.generated
     */
    private String sqlProcess;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_error_proc_log.sql_state
     *
     * @mbg.generated
     */
    private String sqlState;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_error_proc_log.msg_text
     *
     * @mbg.generated
     */
    private String msgText;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_error_proc_log
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_error_proc_log.proc_name
     *
     * @return the value of sys_error_proc_log.proc_name
     *
     * @mbg.generated
     */
    public String getProcName() {
        return procName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_error_proc_log.proc_name
     *
     * @param procName the value for sys_error_proc_log.proc_name
     *
     * @mbg.generated
     */
    public void setProcName(String procName) {
        this.procName = procName == null ? null : procName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_error_proc_log.create_time
     *
     * @return the value of sys_error_proc_log.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_error_proc_log.create_time
     *
     * @param createTime the value for sys_error_proc_log.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_error_proc_log.object_id
     *
     * @return the value of sys_error_proc_log.object_id
     *
     * @mbg.generated
     */
    public String getObjectId() {
        return objectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_error_proc_log.object_id
     *
     * @param objectId the value for sys_error_proc_log.object_id
     *
     * @mbg.generated
     */
    public void setObjectId(String objectId) {
        this.objectId = objectId == null ? null : objectId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_error_proc_log.object_type
     *
     * @return the value of sys_error_proc_log.object_type
     *
     * @mbg.generated
     */
    public String getObjectType() {
        return objectType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_error_proc_log.object_type
     *
     * @param objectType the value for sys_error_proc_log.object_type
     *
     * @mbg.generated
     */
    public void setObjectType(String objectType) {
        this.objectType = objectType == null ? null : objectType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_error_proc_log.sql_process
     *
     * @return the value of sys_error_proc_log.sql_process
     *
     * @mbg.generated
     */
    public String getSqlProcess() {
        return sqlProcess;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_error_proc_log.sql_process
     *
     * @param sqlProcess the value for sys_error_proc_log.sql_process
     *
     * @mbg.generated
     */
    public void setSqlProcess(String sqlProcess) {
        this.sqlProcess = sqlProcess == null ? null : sqlProcess.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_error_proc_log.sql_state
     *
     * @return the value of sys_error_proc_log.sql_state
     *
     * @mbg.generated
     */
    public String getSqlState() {
        return sqlState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_error_proc_log.sql_state
     *
     * @param sqlState the value for sys_error_proc_log.sql_state
     *
     * @mbg.generated
     */
    public void setSqlState(String sqlState) {
        this.sqlState = sqlState == null ? null : sqlState.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_error_proc_log.msg_text
     *
     * @return the value of sys_error_proc_log.msg_text
     *
     * @mbg.generated
     */
    public String getMsgText() {
        return msgText;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_error_proc_log.msg_text
     *
     * @param msgText the value for sys_error_proc_log.msg_text
     *
     * @mbg.generated
     */
    public void setMsgText(String msgText) {
        this.msgText = msgText == null ? null : msgText.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_error_proc_log
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", procName=").append(procName);
        sb.append(", createTime=").append(createTime);
        sb.append(", objectId=").append(objectId);
        sb.append(", objectType=").append(objectType);
        sb.append(", sqlProcess=").append(sqlProcess);
        sb.append(", sqlState=").append(sqlState);
        sb.append(", msgText=").append(msgText);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}