package com.geeker.marketing.dao.micro.generator.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class SysErrorProcLogExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_error_proc_log
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_error_proc_log
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_error_proc_log
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_error_proc_log
     *
     * @mbg.generated
     */
    public SysErrorProcLogExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_error_proc_log
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_error_proc_log
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_error_proc_log
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_error_proc_log
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_error_proc_log
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_error_proc_log
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_error_proc_log
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_error_proc_log
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_error_proc_log
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_error_proc_log
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sys_error_proc_log
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andProcNameIsNull() {
            addCriterion("proc_name is null");
            return (Criteria) this;
        }

        public Criteria andProcNameIsNotNull() {
            addCriterion("proc_name is not null");
            return (Criteria) this;
        }

        public Criteria andProcNameEqualTo(String value) {
            addCriterion("proc_name =", value, "procName");
            return (Criteria) this;
        }

        public Criteria andProcNameNotEqualTo(String value) {
            addCriterion("proc_name <>", value, "procName");
            return (Criteria) this;
        }

        public Criteria andProcNameGreaterThan(String value) {
            addCriterion("proc_name >", value, "procName");
            return (Criteria) this;
        }

        public Criteria andProcNameGreaterThanOrEqualTo(String value) {
            addCriterion("proc_name >=", value, "procName");
            return (Criteria) this;
        }

        public Criteria andProcNameLessThan(String value) {
            addCriterion("proc_name <", value, "procName");
            return (Criteria) this;
        }

        public Criteria andProcNameLessThanOrEqualTo(String value) {
            addCriterion("proc_name <=", value, "procName");
            return (Criteria) this;
        }

        public Criteria andProcNameLike(String value) {
            addCriterion("proc_name like", value, "procName");
            return (Criteria) this;
        }

        public Criteria andProcNameNotLike(String value) {
            addCriterion("proc_name not like", value, "procName");
            return (Criteria) this;
        }

        public Criteria andProcNameIn(List<String> values) {
            addCriterion("proc_name in", values, "procName");
            return (Criteria) this;
        }

        public Criteria andProcNameNotIn(List<String> values) {
            addCriterion("proc_name not in", values, "procName");
            return (Criteria) this;
        }

        public Criteria andProcNameBetween(String value1, String value2) {
            addCriterion("proc_name between", value1, value2, "procName");
            return (Criteria) this;
        }

        public Criteria andProcNameNotBetween(String value1, String value2) {
            addCriterion("proc_name not between", value1, value2, "procName");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andObjectIdIsNull() {
            addCriterion("object_id is null");
            return (Criteria) this;
        }

        public Criteria andObjectIdIsNotNull() {
            addCriterion("object_id is not null");
            return (Criteria) this;
        }

        public Criteria andObjectIdEqualTo(String value) {
            addCriterion("object_id =", value, "objectId");
            return (Criteria) this;
        }

        public Criteria andObjectIdNotEqualTo(String value) {
            addCriterion("object_id <>", value, "objectId");
            return (Criteria) this;
        }

        public Criteria andObjectIdGreaterThan(String value) {
            addCriterion("object_id >", value, "objectId");
            return (Criteria) this;
        }

        public Criteria andObjectIdGreaterThanOrEqualTo(String value) {
            addCriterion("object_id >=", value, "objectId");
            return (Criteria) this;
        }

        public Criteria andObjectIdLessThan(String value) {
            addCriterion("object_id <", value, "objectId");
            return (Criteria) this;
        }

        public Criteria andObjectIdLessThanOrEqualTo(String value) {
            addCriterion("object_id <=", value, "objectId");
            return (Criteria) this;
        }

        public Criteria andObjectIdLike(String value) {
            addCriterion("object_id like", value, "objectId");
            return (Criteria) this;
        }

        public Criteria andObjectIdNotLike(String value) {
            addCriterion("object_id not like", value, "objectId");
            return (Criteria) this;
        }

        public Criteria andObjectIdIn(List<String> values) {
            addCriterion("object_id in", values, "objectId");
            return (Criteria) this;
        }

        public Criteria andObjectIdNotIn(List<String> values) {
            addCriterion("object_id not in", values, "objectId");
            return (Criteria) this;
        }

        public Criteria andObjectIdBetween(String value1, String value2) {
            addCriterion("object_id between", value1, value2, "objectId");
            return (Criteria) this;
        }

        public Criteria andObjectIdNotBetween(String value1, String value2) {
            addCriterion("object_id not between", value1, value2, "objectId");
            return (Criteria) this;
        }

        public Criteria andObjectTypeIsNull() {
            addCriterion("object_type is null");
            return (Criteria) this;
        }

        public Criteria andObjectTypeIsNotNull() {
            addCriterion("object_type is not null");
            return (Criteria) this;
        }

        public Criteria andObjectTypeEqualTo(String value) {
            addCriterion("object_type =", value, "objectType");
            return (Criteria) this;
        }

        public Criteria andObjectTypeNotEqualTo(String value) {
            addCriterion("object_type <>", value, "objectType");
            return (Criteria) this;
        }

        public Criteria andObjectTypeGreaterThan(String value) {
            addCriterion("object_type >", value, "objectType");
            return (Criteria) this;
        }

        public Criteria andObjectTypeGreaterThanOrEqualTo(String value) {
            addCriterion("object_type >=", value, "objectType");
            return (Criteria) this;
        }

        public Criteria andObjectTypeLessThan(String value) {
            addCriterion("object_type <", value, "objectType");
            return (Criteria) this;
        }

        public Criteria andObjectTypeLessThanOrEqualTo(String value) {
            addCriterion("object_type <=", value, "objectType");
            return (Criteria) this;
        }

        public Criteria andObjectTypeLike(String value) {
            addCriterion("object_type like", value, "objectType");
            return (Criteria) this;
        }

        public Criteria andObjectTypeNotLike(String value) {
            addCriterion("object_type not like", value, "objectType");
            return (Criteria) this;
        }

        public Criteria andObjectTypeIn(List<String> values) {
            addCriterion("object_type in", values, "objectType");
            return (Criteria) this;
        }

        public Criteria andObjectTypeNotIn(List<String> values) {
            addCriterion("object_type not in", values, "objectType");
            return (Criteria) this;
        }

        public Criteria andObjectTypeBetween(String value1, String value2) {
            addCriterion("object_type between", value1, value2, "objectType");
            return (Criteria) this;
        }

        public Criteria andObjectTypeNotBetween(String value1, String value2) {
            addCriterion("object_type not between", value1, value2, "objectType");
            return (Criteria) this;
        }

        public Criteria andSqlProcessIsNull() {
            addCriterion("sql_process is null");
            return (Criteria) this;
        }

        public Criteria andSqlProcessIsNotNull() {
            addCriterion("sql_process is not null");
            return (Criteria) this;
        }

        public Criteria andSqlProcessEqualTo(String value) {
            addCriterion("sql_process =", value, "sqlProcess");
            return (Criteria) this;
        }

        public Criteria andSqlProcessNotEqualTo(String value) {
            addCriterion("sql_process <>", value, "sqlProcess");
            return (Criteria) this;
        }

        public Criteria andSqlProcessGreaterThan(String value) {
            addCriterion("sql_process >", value, "sqlProcess");
            return (Criteria) this;
        }

        public Criteria andSqlProcessGreaterThanOrEqualTo(String value) {
            addCriterion("sql_process >=", value, "sqlProcess");
            return (Criteria) this;
        }

        public Criteria andSqlProcessLessThan(String value) {
            addCriterion("sql_process <", value, "sqlProcess");
            return (Criteria) this;
        }

        public Criteria andSqlProcessLessThanOrEqualTo(String value) {
            addCriterion("sql_process <=", value, "sqlProcess");
            return (Criteria) this;
        }

        public Criteria andSqlProcessLike(String value) {
            addCriterion("sql_process like", value, "sqlProcess");
            return (Criteria) this;
        }

        public Criteria andSqlProcessNotLike(String value) {
            addCriterion("sql_process not like", value, "sqlProcess");
            return (Criteria) this;
        }

        public Criteria andSqlProcessIn(List<String> values) {
            addCriterion("sql_process in", values, "sqlProcess");
            return (Criteria) this;
        }

        public Criteria andSqlProcessNotIn(List<String> values) {
            addCriterion("sql_process not in", values, "sqlProcess");
            return (Criteria) this;
        }

        public Criteria andSqlProcessBetween(String value1, String value2) {
            addCriterion("sql_process between", value1, value2, "sqlProcess");
            return (Criteria) this;
        }

        public Criteria andSqlProcessNotBetween(String value1, String value2) {
            addCriterion("sql_process not between", value1, value2, "sqlProcess");
            return (Criteria) this;
        }

        public Criteria andSqlStateIsNull() {
            addCriterion("sql_state is null");
            return (Criteria) this;
        }

        public Criteria andSqlStateIsNotNull() {
            addCriterion("sql_state is not null");
            return (Criteria) this;
        }

        public Criteria andSqlStateEqualTo(String value) {
            addCriterion("sql_state =", value, "sqlState");
            return (Criteria) this;
        }

        public Criteria andSqlStateNotEqualTo(String value) {
            addCriterion("sql_state <>", value, "sqlState");
            return (Criteria) this;
        }

        public Criteria andSqlStateGreaterThan(String value) {
            addCriterion("sql_state >", value, "sqlState");
            return (Criteria) this;
        }

        public Criteria andSqlStateGreaterThanOrEqualTo(String value) {
            addCriterion("sql_state >=", value, "sqlState");
            return (Criteria) this;
        }

        public Criteria andSqlStateLessThan(String value) {
            addCriterion("sql_state <", value, "sqlState");
            return (Criteria) this;
        }

        public Criteria andSqlStateLessThanOrEqualTo(String value) {
            addCriterion("sql_state <=", value, "sqlState");
            return (Criteria) this;
        }

        public Criteria andSqlStateLike(String value) {
            addCriterion("sql_state like", value, "sqlState");
            return (Criteria) this;
        }

        public Criteria andSqlStateNotLike(String value) {
            addCriterion("sql_state not like", value, "sqlState");
            return (Criteria) this;
        }

        public Criteria andSqlStateIn(List<String> values) {
            addCriterion("sql_state in", values, "sqlState");
            return (Criteria) this;
        }

        public Criteria andSqlStateNotIn(List<String> values) {
            addCriterion("sql_state not in", values, "sqlState");
            return (Criteria) this;
        }

        public Criteria andSqlStateBetween(String value1, String value2) {
            addCriterion("sql_state between", value1, value2, "sqlState");
            return (Criteria) this;
        }

        public Criteria andSqlStateNotBetween(String value1, String value2) {
            addCriterion("sql_state not between", value1, value2, "sqlState");
            return (Criteria) this;
        }

        public Criteria andMsgTextIsNull() {
            addCriterion("msg_text is null");
            return (Criteria) this;
        }

        public Criteria andMsgTextIsNotNull() {
            addCriterion("msg_text is not null");
            return (Criteria) this;
        }

        public Criteria andMsgTextEqualTo(String value) {
            addCriterion("msg_text =", value, "msgText");
            return (Criteria) this;
        }

        public Criteria andMsgTextNotEqualTo(String value) {
            addCriterion("msg_text <>", value, "msgText");
            return (Criteria) this;
        }

        public Criteria andMsgTextGreaterThan(String value) {
            addCriterion("msg_text >", value, "msgText");
            return (Criteria) this;
        }

        public Criteria andMsgTextGreaterThanOrEqualTo(String value) {
            addCriterion("msg_text >=", value, "msgText");
            return (Criteria) this;
        }

        public Criteria andMsgTextLessThan(String value) {
            addCriterion("msg_text <", value, "msgText");
            return (Criteria) this;
        }

        public Criteria andMsgTextLessThanOrEqualTo(String value) {
            addCriterion("msg_text <=", value, "msgText");
            return (Criteria) this;
        }

        public Criteria andMsgTextLike(String value) {
            addCriterion("msg_text like", value, "msgText");
            return (Criteria) this;
        }

        public Criteria andMsgTextNotLike(String value) {
            addCriterion("msg_text not like", value, "msgText");
            return (Criteria) this;
        }

        public Criteria andMsgTextIn(List<String> values) {
            addCriterion("msg_text in", values, "msgText");
            return (Criteria) this;
        }

        public Criteria andMsgTextNotIn(List<String> values) {
            addCriterion("msg_text not in", values, "msgText");
            return (Criteria) this;
        }

        public Criteria andMsgTextBetween(String value1, String value2) {
            addCriterion("msg_text between", value1, value2, "msgText");
            return (Criteria) this;
        }

        public Criteria andMsgTextNotBetween(String value1, String value2) {
            addCriterion("msg_text not between", value1, value2, "msgText");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sys_error_proc_log
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sys_error_proc_log
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}