package com.geeker.marketing.dao.micro.generator.model;

import java.io.Serializable;
import java.util.Date;

public class WxAccount implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_account.device_id
     *
     * @mbg.generated
     */
    private String deviceId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_account.com_id
     *
     * @mbg.generated
     */
    private Integer comId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_account.wx_uin_id
     *
     * @mbg.generated
     */
    private String wxUinId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_account.wx_id
     *
     * @mbg.generated
     */
    private String wxId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_account.wx_login
     *
     * @mbg.generated
     */
    private String wxLogin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_account.nickname
     *
     * @mbg.generated
     */
    private String nickname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_account.head_img_uri
     *
     * @mbg.generated
     */
    private String headImgUri;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_account.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_account.status
     *
     * @mbg.generated
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table wx_account
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_account.device_id
     *
     * @return the value of wx_account.device_id
     *
     * @mbg.generated
     */
    public String getDeviceId() {
        return deviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_account.device_id
     *
     * @param deviceId the value for wx_account.device_id
     *
     * @mbg.generated
     */
    public void setDeviceId(String deviceId) {
        this.deviceId = deviceId == null ? null : deviceId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_account.com_id
     *
     * @return the value of wx_account.com_id
     *
     * @mbg.generated
     */
    public Integer getComId() {
        return comId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_account.com_id
     *
     * @param comId the value for wx_account.com_id
     *
     * @mbg.generated
     */
    public void setComId(Integer comId) {
        this.comId = comId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_account.wx_uin_id
     *
     * @return the value of wx_account.wx_uin_id
     *
     * @mbg.generated
     */
    public String getWxUinId() {
        return wxUinId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_account.wx_uin_id
     *
     * @param wxUinId the value for wx_account.wx_uin_id
     *
     * @mbg.generated
     */
    public void setWxUinId(String wxUinId) {
        this.wxUinId = wxUinId == null ? null : wxUinId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_account.wx_id
     *
     * @return the value of wx_account.wx_id
     *
     * @mbg.generated
     */
    public String getWxId() {
        return wxId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_account.wx_id
     *
     * @param wxId the value for wx_account.wx_id
     *
     * @mbg.generated
     */
    public void setWxId(String wxId) {
        this.wxId = wxId == null ? null : wxId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_account.wx_login
     *
     * @return the value of wx_account.wx_login
     *
     * @mbg.generated
     */
    public String getWxLogin() {
        return wxLogin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_account.wx_login
     *
     * @param wxLogin the value for wx_account.wx_login
     *
     * @mbg.generated
     */
    public void setWxLogin(String wxLogin) {
        this.wxLogin = wxLogin == null ? null : wxLogin.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_account.nickname
     *
     * @return the value of wx_account.nickname
     *
     * @mbg.generated
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_account.nickname
     *
     * @param nickname the value for wx_account.nickname
     *
     * @mbg.generated
     */
    public void setNickname(String nickname) {
        this.nickname = nickname == null ? null : nickname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_account.head_img_uri
     *
     * @return the value of wx_account.head_img_uri
     *
     * @mbg.generated
     */
    public String getHeadImgUri() {
        return headImgUri;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_account.head_img_uri
     *
     * @param headImgUri the value for wx_account.head_img_uri
     *
     * @mbg.generated
     */
    public void setHeadImgUri(String headImgUri) {
        this.headImgUri = headImgUri == null ? null : headImgUri.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_account.create_time
     *
     * @return the value of wx_account.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_account.create_time
     *
     * @param createTime the value for wx_account.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_account.status
     *
     * @return the value of wx_account.status
     *
     * @mbg.generated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_account.status
     *
     * @param status the value for wx_account.status
     *
     * @mbg.generated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_account
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", deviceId=").append(deviceId);
        sb.append(", comId=").append(comId);
        sb.append(", wxUinId=").append(wxUinId);
        sb.append(", wxId=").append(wxId);
        sb.append(", wxLogin=").append(wxLogin);
        sb.append(", nickname=").append(nickname);
        sb.append(", headImgUri=").append(headImgUri);
        sb.append(", createTime=").append(createTime);
        sb.append(", status=").append(status);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}