package com.geeker.marketing.dao.micro.generator.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class WxFansExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table wx_fans
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table wx_fans
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table wx_fans
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_fans
     *
     * @mbg.generated
     */
    public WxFansExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_fans
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_fans
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_fans
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_fans
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_fans
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_fans
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_fans
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_fans
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_fans
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_fans
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table wx_fans
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andWxUinIdIsNull() {
            addCriterion("wx_uin_id is null");
            return (Criteria) this;
        }

        public Criteria andWxUinIdIsNotNull() {
            addCriterion("wx_uin_id is not null");
            return (Criteria) this;
        }

        public Criteria andWxUinIdEqualTo(String value) {
            addCriterion("wx_uin_id =", value, "wxUinId");
            return (Criteria) this;
        }

        public Criteria andWxUinIdNotEqualTo(String value) {
            addCriterion("wx_uin_id <>", value, "wxUinId");
            return (Criteria) this;
        }

        public Criteria andWxUinIdGreaterThan(String value) {
            addCriterion("wx_uin_id >", value, "wxUinId");
            return (Criteria) this;
        }

        public Criteria andWxUinIdGreaterThanOrEqualTo(String value) {
            addCriterion("wx_uin_id >=", value, "wxUinId");
            return (Criteria) this;
        }

        public Criteria andWxUinIdLessThan(String value) {
            addCriterion("wx_uin_id <", value, "wxUinId");
            return (Criteria) this;
        }

        public Criteria andWxUinIdLessThanOrEqualTo(String value) {
            addCriterion("wx_uin_id <=", value, "wxUinId");
            return (Criteria) this;
        }

        public Criteria andWxUinIdLike(String value) {
            addCriterion("wx_uin_id like", value, "wxUinId");
            return (Criteria) this;
        }

        public Criteria andWxUinIdNotLike(String value) {
            addCriterion("wx_uin_id not like", value, "wxUinId");
            return (Criteria) this;
        }

        public Criteria andWxUinIdIn(List<String> values) {
            addCriterion("wx_uin_id in", values, "wxUinId");
            return (Criteria) this;
        }

        public Criteria andWxUinIdNotIn(List<String> values) {
            addCriterion("wx_uin_id not in", values, "wxUinId");
            return (Criteria) this;
        }

        public Criteria andWxUinIdBetween(String value1, String value2) {
            addCriterion("wx_uin_id between", value1, value2, "wxUinId");
            return (Criteria) this;
        }

        public Criteria andWxUinIdNotBetween(String value1, String value2) {
            addCriterion("wx_uin_id not between", value1, value2, "wxUinId");
            return (Criteria) this;
        }

        public Criteria andWxIdIsNull() {
            addCriterion("wx_id is null");
            return (Criteria) this;
        }

        public Criteria andWxIdIsNotNull() {
            addCriterion("wx_id is not null");
            return (Criteria) this;
        }

        public Criteria andWxIdEqualTo(String value) {
            addCriterion("wx_id =", value, "wxId");
            return (Criteria) this;
        }

        public Criteria andWxIdNotEqualTo(String value) {
            addCriterion("wx_id <>", value, "wxId");
            return (Criteria) this;
        }

        public Criteria andWxIdGreaterThan(String value) {
            addCriterion("wx_id >", value, "wxId");
            return (Criteria) this;
        }

        public Criteria andWxIdGreaterThanOrEqualTo(String value) {
            addCriterion("wx_id >=", value, "wxId");
            return (Criteria) this;
        }

        public Criteria andWxIdLessThan(String value) {
            addCriterion("wx_id <", value, "wxId");
            return (Criteria) this;
        }

        public Criteria andWxIdLessThanOrEqualTo(String value) {
            addCriterion("wx_id <=", value, "wxId");
            return (Criteria) this;
        }

        public Criteria andWxIdLike(String value) {
            addCriterion("wx_id like", value, "wxId");
            return (Criteria) this;
        }

        public Criteria andWxIdNotLike(String value) {
            addCriterion("wx_id not like", value, "wxId");
            return (Criteria) this;
        }

        public Criteria andWxIdIn(List<String> values) {
            addCriterion("wx_id in", values, "wxId");
            return (Criteria) this;
        }

        public Criteria andWxIdNotIn(List<String> values) {
            addCriterion("wx_id not in", values, "wxId");
            return (Criteria) this;
        }

        public Criteria andWxIdBetween(String value1, String value2) {
            addCriterion("wx_id between", value1, value2, "wxId");
            return (Criteria) this;
        }

        public Criteria andWxIdNotBetween(String value1, String value2) {
            addCriterion("wx_id not between", value1, value2, "wxId");
            return (Criteria) this;
        }

        public Criteria andNicknameIsNull() {
            addCriterion("nickname is null");
            return (Criteria) this;
        }

        public Criteria andNicknameIsNotNull() {
            addCriterion("nickname is not null");
            return (Criteria) this;
        }

        public Criteria andNicknameEqualTo(String value) {
            addCriterion("nickname =", value, "nickname");
            return (Criteria) this;
        }

        public Criteria andNicknameNotEqualTo(String value) {
            addCriterion("nickname <>", value, "nickname");
            return (Criteria) this;
        }

        public Criteria andNicknameGreaterThan(String value) {
            addCriterion("nickname >", value, "nickname");
            return (Criteria) this;
        }

        public Criteria andNicknameGreaterThanOrEqualTo(String value) {
            addCriterion("nickname >=", value, "nickname");
            return (Criteria) this;
        }

        public Criteria andNicknameLessThan(String value) {
            addCriterion("nickname <", value, "nickname");
            return (Criteria) this;
        }

        public Criteria andNicknameLessThanOrEqualTo(String value) {
            addCriterion("nickname <=", value, "nickname");
            return (Criteria) this;
        }

        public Criteria andNicknameLike(String value) {
            addCriterion("nickname like", value, "nickname");
            return (Criteria) this;
        }

        public Criteria andNicknameNotLike(String value) {
            addCriterion("nickname not like", value, "nickname");
            return (Criteria) this;
        }

        public Criteria andNicknameIn(List<String> values) {
            addCriterion("nickname in", values, "nickname");
            return (Criteria) this;
        }

        public Criteria andNicknameNotIn(List<String> values) {
            addCriterion("nickname not in", values, "nickname");
            return (Criteria) this;
        }

        public Criteria andNicknameBetween(String value1, String value2) {
            addCriterion("nickname between", value1, value2, "nickname");
            return (Criteria) this;
        }

        public Criteria andNicknameNotBetween(String value1, String value2) {
            addCriterion("nickname not between", value1, value2, "nickname");
            return (Criteria) this;
        }

        public Criteria andHeadImgUriIsNull() {
            addCriterion("head_img_uri is null");
            return (Criteria) this;
        }

        public Criteria andHeadImgUriIsNotNull() {
            addCriterion("head_img_uri is not null");
            return (Criteria) this;
        }

        public Criteria andHeadImgUriEqualTo(String value) {
            addCriterion("head_img_uri =", value, "headImgUri");
            return (Criteria) this;
        }

        public Criteria andHeadImgUriNotEqualTo(String value) {
            addCriterion("head_img_uri <>", value, "headImgUri");
            return (Criteria) this;
        }

        public Criteria andHeadImgUriGreaterThan(String value) {
            addCriterion("head_img_uri >", value, "headImgUri");
            return (Criteria) this;
        }

        public Criteria andHeadImgUriGreaterThanOrEqualTo(String value) {
            addCriterion("head_img_uri >=", value, "headImgUri");
            return (Criteria) this;
        }

        public Criteria andHeadImgUriLessThan(String value) {
            addCriterion("head_img_uri <", value, "headImgUri");
            return (Criteria) this;
        }

        public Criteria andHeadImgUriLessThanOrEqualTo(String value) {
            addCriterion("head_img_uri <=", value, "headImgUri");
            return (Criteria) this;
        }

        public Criteria andHeadImgUriLike(String value) {
            addCriterion("head_img_uri like", value, "headImgUri");
            return (Criteria) this;
        }

        public Criteria andHeadImgUriNotLike(String value) {
            addCriterion("head_img_uri not like", value, "headImgUri");
            return (Criteria) this;
        }

        public Criteria andHeadImgUriIn(List<String> values) {
            addCriterion("head_img_uri in", values, "headImgUri");
            return (Criteria) this;
        }

        public Criteria andHeadImgUriNotIn(List<String> values) {
            addCriterion("head_img_uri not in", values, "headImgUri");
            return (Criteria) this;
        }

        public Criteria andHeadImgUriBetween(String value1, String value2) {
            addCriterion("head_img_uri between", value1, value2, "headImgUri");
            return (Criteria) this;
        }

        public Criteria andHeadImgUriNotBetween(String value1, String value2) {
            addCriterion("head_img_uri not between", value1, value2, "headImgUri");
            return (Criteria) this;
        }

        public Criteria andSexIsNull() {
            addCriterion("sex is null");
            return (Criteria) this;
        }

        public Criteria andSexIsNotNull() {
            addCriterion("sex is not null");
            return (Criteria) this;
        }

        public Criteria andSexEqualTo(String value) {
            addCriterion("sex =", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexNotEqualTo(String value) {
            addCriterion("sex <>", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexGreaterThan(String value) {
            addCriterion("sex >", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexGreaterThanOrEqualTo(String value) {
            addCriterion("sex >=", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexLessThan(String value) {
            addCriterion("sex <", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexLessThanOrEqualTo(String value) {
            addCriterion("sex <=", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexLike(String value) {
            addCriterion("sex like", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexNotLike(String value) {
            addCriterion("sex not like", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexIn(List<String> values) {
            addCriterion("sex in", values, "sex");
            return (Criteria) this;
        }

        public Criteria andSexNotIn(List<String> values) {
            addCriterion("sex not in", values, "sex");
            return (Criteria) this;
        }

        public Criteria andSexBetween(String value1, String value2) {
            addCriterion("sex between", value1, value2, "sex");
            return (Criteria) this;
        }

        public Criteria andSexNotBetween(String value1, String value2) {
            addCriterion("sex not between", value1, value2, "sex");
            return (Criteria) this;
        }

        public Criteria andCountryIsNull() {
            addCriterion("country is null");
            return (Criteria) this;
        }

        public Criteria andCountryIsNotNull() {
            addCriterion("country is not null");
            return (Criteria) this;
        }

        public Criteria andCountryEqualTo(String value) {
            addCriterion("country =", value, "country");
            return (Criteria) this;
        }

        public Criteria andCountryNotEqualTo(String value) {
            addCriterion("country <>", value, "country");
            return (Criteria) this;
        }

        public Criteria andCountryGreaterThan(String value) {
            addCriterion("country >", value, "country");
            return (Criteria) this;
        }

        public Criteria andCountryGreaterThanOrEqualTo(String value) {
            addCriterion("country >=", value, "country");
            return (Criteria) this;
        }

        public Criteria andCountryLessThan(String value) {
            addCriterion("country <", value, "country");
            return (Criteria) this;
        }

        public Criteria andCountryLessThanOrEqualTo(String value) {
            addCriterion("country <=", value, "country");
            return (Criteria) this;
        }

        public Criteria andCountryLike(String value) {
            addCriterion("country like", value, "country");
            return (Criteria) this;
        }

        public Criteria andCountryNotLike(String value) {
            addCriterion("country not like", value, "country");
            return (Criteria) this;
        }

        public Criteria andCountryIn(List<String> values) {
            addCriterion("country in", values, "country");
            return (Criteria) this;
        }

        public Criteria andCountryNotIn(List<String> values) {
            addCriterion("country not in", values, "country");
            return (Criteria) this;
        }

        public Criteria andCountryBetween(String value1, String value2) {
            addCriterion("country between", value1, value2, "country");
            return (Criteria) this;
        }

        public Criteria andCountryNotBetween(String value1, String value2) {
            addCriterion("country not between", value1, value2, "country");
            return (Criteria) this;
        }

        public Criteria andProvinceIsNull() {
            addCriterion("province is null");
            return (Criteria) this;
        }

        public Criteria andProvinceIsNotNull() {
            addCriterion("province is not null");
            return (Criteria) this;
        }

        public Criteria andProvinceEqualTo(String value) {
            addCriterion("province =", value, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceNotEqualTo(String value) {
            addCriterion("province <>", value, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceGreaterThan(String value) {
            addCriterion("province >", value, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceGreaterThanOrEqualTo(String value) {
            addCriterion("province >=", value, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceLessThan(String value) {
            addCriterion("province <", value, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceLessThanOrEqualTo(String value) {
            addCriterion("province <=", value, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceLike(String value) {
            addCriterion("province like", value, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceNotLike(String value) {
            addCriterion("province not like", value, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceIn(List<String> values) {
            addCriterion("province in", values, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceNotIn(List<String> values) {
            addCriterion("province not in", values, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceBetween(String value1, String value2) {
            addCriterion("province between", value1, value2, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceNotBetween(String value1, String value2) {
            addCriterion("province not between", value1, value2, "province");
            return (Criteria) this;
        }

        public Criteria andCityIsNull() {
            addCriterion("city is null");
            return (Criteria) this;
        }

        public Criteria andCityIsNotNull() {
            addCriterion("city is not null");
            return (Criteria) this;
        }

        public Criteria andCityEqualTo(String value) {
            addCriterion("city =", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityNotEqualTo(String value) {
            addCriterion("city <>", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityGreaterThan(String value) {
            addCriterion("city >", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityGreaterThanOrEqualTo(String value) {
            addCriterion("city >=", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityLessThan(String value) {
            addCriterion("city <", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityLessThanOrEqualTo(String value) {
            addCriterion("city <=", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityLike(String value) {
            addCriterion("city like", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityNotLike(String value) {
            addCriterion("city not like", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityIn(List<String> values) {
            addCriterion("city in", values, "city");
            return (Criteria) this;
        }

        public Criteria andCityNotIn(List<String> values) {
            addCriterion("city not in", values, "city");
            return (Criteria) this;
        }

        public Criteria andCityBetween(String value1, String value2) {
            addCriterion("city between", value1, value2, "city");
            return (Criteria) this;
        }

        public Criteria andCityNotBetween(String value1, String value2) {
            addCriterion("city not between", value1, value2, "city");
            return (Criteria) this;
        }

        public Criteria andSignatureIsNull() {
            addCriterion("signature is null");
            return (Criteria) this;
        }

        public Criteria andSignatureIsNotNull() {
            addCriterion("signature is not null");
            return (Criteria) this;
        }

        public Criteria andSignatureEqualTo(String value) {
            addCriterion("signature =", value, "signature");
            return (Criteria) this;
        }

        public Criteria andSignatureNotEqualTo(String value) {
            addCriterion("signature <>", value, "signature");
            return (Criteria) this;
        }

        public Criteria andSignatureGreaterThan(String value) {
            addCriterion("signature >", value, "signature");
            return (Criteria) this;
        }

        public Criteria andSignatureGreaterThanOrEqualTo(String value) {
            addCriterion("signature >=", value, "signature");
            return (Criteria) this;
        }

        public Criteria andSignatureLessThan(String value) {
            addCriterion("signature <", value, "signature");
            return (Criteria) this;
        }

        public Criteria andSignatureLessThanOrEqualTo(String value) {
            addCriterion("signature <=", value, "signature");
            return (Criteria) this;
        }

        public Criteria andSignatureLike(String value) {
            addCriterion("signature like", value, "signature");
            return (Criteria) this;
        }

        public Criteria andSignatureNotLike(String value) {
            addCriterion("signature not like", value, "signature");
            return (Criteria) this;
        }

        public Criteria andSignatureIn(List<String> values) {
            addCriterion("signature in", values, "signature");
            return (Criteria) this;
        }

        public Criteria andSignatureNotIn(List<String> values) {
            addCriterion("signature not in", values, "signature");
            return (Criteria) this;
        }

        public Criteria andSignatureBetween(String value1, String value2) {
            addCriterion("signature between", value1, value2, "signature");
            return (Criteria) this;
        }

        public Criteria andSignatureNotBetween(String value1, String value2) {
            addCriterion("signature not between", value1, value2, "signature");
            return (Criteria) this;
        }

        public Criteria andV1NameIsNull() {
            addCriterion("v1_name is null");
            return (Criteria) this;
        }

        public Criteria andV1NameIsNotNull() {
            addCriterion("v1_name is not null");
            return (Criteria) this;
        }

        public Criteria andV1NameEqualTo(String value) {
            addCriterion("v1_name =", value, "v1Name");
            return (Criteria) this;
        }

        public Criteria andV1NameNotEqualTo(String value) {
            addCriterion("v1_name <>", value, "v1Name");
            return (Criteria) this;
        }

        public Criteria andV1NameGreaterThan(String value) {
            addCriterion("v1_name >", value, "v1Name");
            return (Criteria) this;
        }

        public Criteria andV1NameGreaterThanOrEqualTo(String value) {
            addCriterion("v1_name >=", value, "v1Name");
            return (Criteria) this;
        }

        public Criteria andV1NameLessThan(String value) {
            addCriterion("v1_name <", value, "v1Name");
            return (Criteria) this;
        }

        public Criteria andV1NameLessThanOrEqualTo(String value) {
            addCriterion("v1_name <=", value, "v1Name");
            return (Criteria) this;
        }

        public Criteria andV1NameLike(String value) {
            addCriterion("v1_name like", value, "v1Name");
            return (Criteria) this;
        }

        public Criteria andV1NameNotLike(String value) {
            addCriterion("v1_name not like", value, "v1Name");
            return (Criteria) this;
        }

        public Criteria andV1NameIn(List<String> values) {
            addCriterion("v1_name in", values, "v1Name");
            return (Criteria) this;
        }

        public Criteria andV1NameNotIn(List<String> values) {
            addCriterion("v1_name not in", values, "v1Name");
            return (Criteria) this;
        }

        public Criteria andV1NameBetween(String value1, String value2) {
            addCriterion("v1_name between", value1, value2, "v1Name");
            return (Criteria) this;
        }

        public Criteria andV1NameNotBetween(String value1, String value2) {
            addCriterion("v1_name not between", value1, value2, "v1Name");
            return (Criteria) this;
        }

        public Criteria andIsZombieFanIsNull() {
            addCriterion("is_zombie_fan is null");
            return (Criteria) this;
        }

        public Criteria andIsZombieFanIsNotNull() {
            addCriterion("is_zombie_fan is not null");
            return (Criteria) this;
        }

        public Criteria andIsZombieFanEqualTo(Boolean value) {
            addCriterion("is_zombie_fan =", value, "isZombieFan");
            return (Criteria) this;
        }

        public Criteria andIsZombieFanNotEqualTo(Boolean value) {
            addCriterion("is_zombie_fan <>", value, "isZombieFan");
            return (Criteria) this;
        }

        public Criteria andIsZombieFanGreaterThan(Boolean value) {
            addCriterion("is_zombie_fan >", value, "isZombieFan");
            return (Criteria) this;
        }

        public Criteria andIsZombieFanGreaterThanOrEqualTo(Boolean value) {
            addCriterion("is_zombie_fan >=", value, "isZombieFan");
            return (Criteria) this;
        }

        public Criteria andIsZombieFanLessThan(Boolean value) {
            addCriterion("is_zombie_fan <", value, "isZombieFan");
            return (Criteria) this;
        }

        public Criteria andIsZombieFanLessThanOrEqualTo(Boolean value) {
            addCriterion("is_zombie_fan <=", value, "isZombieFan");
            return (Criteria) this;
        }

        public Criteria andIsZombieFanIn(List<Boolean> values) {
            addCriterion("is_zombie_fan in", values, "isZombieFan");
            return (Criteria) this;
        }

        public Criteria andIsZombieFanNotIn(List<Boolean> values) {
            addCriterion("is_zombie_fan not in", values, "isZombieFan");
            return (Criteria) this;
        }

        public Criteria andIsZombieFanBetween(Boolean value1, Boolean value2) {
            addCriterion("is_zombie_fan between", value1, value2, "isZombieFan");
            return (Criteria) this;
        }

        public Criteria andIsZombieFanNotBetween(Boolean value1, Boolean value2) {
            addCriterion("is_zombie_fan not between", value1, value2, "isZombieFan");
            return (Criteria) this;
        }

        public Criteria andFansTypeIsNull() {
            addCriterion("fans_type is null");
            return (Criteria) this;
        }

        public Criteria andFansTypeIsNotNull() {
            addCriterion("fans_type is not null");
            return (Criteria) this;
        }

        public Criteria andFansTypeEqualTo(String value) {
            addCriterion("fans_type =", value, "fansType");
            return (Criteria) this;
        }

        public Criteria andFansTypeNotEqualTo(String value) {
            addCriterion("fans_type <>", value, "fansType");
            return (Criteria) this;
        }

        public Criteria andFansTypeGreaterThan(String value) {
            addCriterion("fans_type >", value, "fansType");
            return (Criteria) this;
        }

        public Criteria andFansTypeGreaterThanOrEqualTo(String value) {
            addCriterion("fans_type >=", value, "fansType");
            return (Criteria) this;
        }

        public Criteria andFansTypeLessThan(String value) {
            addCriterion("fans_type <", value, "fansType");
            return (Criteria) this;
        }

        public Criteria andFansTypeLessThanOrEqualTo(String value) {
            addCriterion("fans_type <=", value, "fansType");
            return (Criteria) this;
        }

        public Criteria andFansTypeLike(String value) {
            addCriterion("fans_type like", value, "fansType");
            return (Criteria) this;
        }

        public Criteria andFansTypeNotLike(String value) {
            addCriterion("fans_type not like", value, "fansType");
            return (Criteria) this;
        }

        public Criteria andFansTypeIn(List<String> values) {
            addCriterion("fans_type in", values, "fansType");
            return (Criteria) this;
        }

        public Criteria andFansTypeNotIn(List<String> values) {
            addCriterion("fans_type not in", values, "fansType");
            return (Criteria) this;
        }

        public Criteria andFansTypeBetween(String value1, String value2) {
            addCriterion("fans_type between", value1, value2, "fansType");
            return (Criteria) this;
        }

        public Criteria andFansTypeNotBetween(String value1, String value2) {
            addCriterion("fans_type not between", value1, value2, "fansType");
            return (Criteria) this;
        }

        public Criteria andFansNumIsNull() {
            addCriterion("fans_num is null");
            return (Criteria) this;
        }

        public Criteria andFansNumIsNotNull() {
            addCriterion("fans_num is not null");
            return (Criteria) this;
        }

        public Criteria andFansNumEqualTo(Integer value) {
            addCriterion("fans_num =", value, "fansNum");
            return (Criteria) this;
        }

        public Criteria andFansNumNotEqualTo(Integer value) {
            addCriterion("fans_num <>", value, "fansNum");
            return (Criteria) this;
        }

        public Criteria andFansNumGreaterThan(Integer value) {
            addCriterion("fans_num >", value, "fansNum");
            return (Criteria) this;
        }

        public Criteria andFansNumGreaterThanOrEqualTo(Integer value) {
            addCriterion("fans_num >=", value, "fansNum");
            return (Criteria) this;
        }

        public Criteria andFansNumLessThan(Integer value) {
            addCriterion("fans_num <", value, "fansNum");
            return (Criteria) this;
        }

        public Criteria andFansNumLessThanOrEqualTo(Integer value) {
            addCriterion("fans_num <=", value, "fansNum");
            return (Criteria) this;
        }

        public Criteria andFansNumIn(List<Integer> values) {
            addCriterion("fans_num in", values, "fansNum");
            return (Criteria) this;
        }

        public Criteria andFansNumNotIn(List<Integer> values) {
            addCriterion("fans_num not in", values, "fansNum");
            return (Criteria) this;
        }

        public Criteria andFansNumBetween(Integer value1, Integer value2) {
            addCriterion("fans_num between", value1, value2, "fansNum");
            return (Criteria) this;
        }

        public Criteria andFansNumNotBetween(Integer value1, Integer value2) {
            addCriterion("fans_num not between", value1, value2, "fansNum");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("update_time =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("update_time <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("update_time >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("update_time >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("update_time <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("update_time <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("update_time in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("update_time not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("update_time between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("update_time not between", value1, value2, "updateTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table wx_fans
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table wx_fans
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}