package com.geeker.marketing.dao.micro.generator.model;

import java.io.Serializable;
import java.util.Date;

public class WxGroupFans implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_group_fans.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_group_fans.wx_uin_id
     *
     * @mbg.generated
     */
    private String wxUinId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_group_fans.wx_group_id
     *
     * @mbg.generated
     */
    private String wxGroupId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_group_fans.wx_id
     *
     * @mbg.generated
     */
    private String wxId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_group_fans.nickname
     *
     * @mbg.generated
     */
    private String nickname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_group_fans.head_img_uri
     *
     * @mbg.generated
     */
    private String headImgUri;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_group_fans.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_group_fans.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table wx_group_fans
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_group_fans.id
     *
     * @return the value of wx_group_fans.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_group_fans.id
     *
     * @param id the value for wx_group_fans.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_group_fans.wx_uin_id
     *
     * @return the value of wx_group_fans.wx_uin_id
     *
     * @mbg.generated
     */
    public String getWxUinId() {
        return wxUinId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_group_fans.wx_uin_id
     *
     * @param wxUinId the value for wx_group_fans.wx_uin_id
     *
     * @mbg.generated
     */
    public void setWxUinId(String wxUinId) {
        this.wxUinId = wxUinId == null ? null : wxUinId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_group_fans.wx_group_id
     *
     * @return the value of wx_group_fans.wx_group_id
     *
     * @mbg.generated
     */
    public String getWxGroupId() {
        return wxGroupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_group_fans.wx_group_id
     *
     * @param wxGroupId the value for wx_group_fans.wx_group_id
     *
     * @mbg.generated
     */
    public void setWxGroupId(String wxGroupId) {
        this.wxGroupId = wxGroupId == null ? null : wxGroupId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_group_fans.wx_id
     *
     * @return the value of wx_group_fans.wx_id
     *
     * @mbg.generated
     */
    public String getWxId() {
        return wxId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_group_fans.wx_id
     *
     * @param wxId the value for wx_group_fans.wx_id
     *
     * @mbg.generated
     */
    public void setWxId(String wxId) {
        this.wxId = wxId == null ? null : wxId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_group_fans.nickname
     *
     * @return the value of wx_group_fans.nickname
     *
     * @mbg.generated
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_group_fans.nickname
     *
     * @param nickname the value for wx_group_fans.nickname
     *
     * @mbg.generated
     */
    public void setNickname(String nickname) {
        this.nickname = nickname == null ? null : nickname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_group_fans.head_img_uri
     *
     * @return the value of wx_group_fans.head_img_uri
     *
     * @mbg.generated
     */
    public String getHeadImgUri() {
        return headImgUri;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_group_fans.head_img_uri
     *
     * @param headImgUri the value for wx_group_fans.head_img_uri
     *
     * @mbg.generated
     */
    public void setHeadImgUri(String headImgUri) {
        this.headImgUri = headImgUri == null ? null : headImgUri.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_group_fans.create_time
     *
     * @return the value of wx_group_fans.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_group_fans.create_time
     *
     * @param createTime the value for wx_group_fans.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_group_fans.update_time
     *
     * @return the value of wx_group_fans.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_group_fans.update_time
     *
     * @param updateTime the value for wx_group_fans.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_group_fans
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", wxUinId=").append(wxUinId);
        sb.append(", wxGroupId=").append(wxGroupId);
        sb.append(", wxId=").append(wxId);
        sb.append(", nickname=").append(nickname);
        sb.append(", headImgUri=").append(headImgUri);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}