package com.geeker.marketing.dao.micro.generator.model;

import java.io.Serializable;
import java.util.Date;

public class WxMsg implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_msg.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_msg.wx_uin_id
     *
     * @mbg.generated
     */
    private String wxUinId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_msg.com_id
     *
     * @mbg.generated
     */
    private Integer comId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_msg.wx_id
     *
     * @mbg.generated
     */
    private String wxId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_msg.wx_group_id
     *
     * @mbg.generated
     */
    private String wxGroupId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_msg.msg_image_uri
     *
     * @mbg.generated
     */
    private String msgImageUri;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_msg.msg_text
     *
     * @mbg.generated
     */
    private String msgText;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_msg.msg_type
     *
     * @mbg.generated
     */
    private String msgType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_msg.fans_type
     *
     * @mbg.generated
     */
    private String fansType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_msg.msg_direct
     *
     * @mbg.generated
     */
    private Boolean msgDirect;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_msg.msg_platform
     *
     * @mbg.generated
     */
    private Boolean msgPlatform;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_msg.micro_serivce
     *
     * @mbg.generated
     */
    private String microSerivce;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_msg.status
     *
     * @mbg.generated
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_msg.receive_time
     *
     * @mbg.generated
     */
    private Date receiveTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_msg.send_time
     *
     * @mbg.generated
     */
    private Date sendTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_msg.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table wx_msg
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_msg.id
     *
     * @return the value of wx_msg.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_msg.id
     *
     * @param id the value for wx_msg.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_msg.wx_uin_id
     *
     * @return the value of wx_msg.wx_uin_id
     *
     * @mbg.generated
     */
    public String getWxUinId() {
        return wxUinId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_msg.wx_uin_id
     *
     * @param wxUinId the value for wx_msg.wx_uin_id
     *
     * @mbg.generated
     */
    public void setWxUinId(String wxUinId) {
        this.wxUinId = wxUinId == null ? null : wxUinId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_msg.com_id
     *
     * @return the value of wx_msg.com_id
     *
     * @mbg.generated
     */
    public Integer getComId() {
        return comId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_msg.com_id
     *
     * @param comId the value for wx_msg.com_id
     *
     * @mbg.generated
     */
    public void setComId(Integer comId) {
        this.comId = comId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_msg.wx_id
     *
     * @return the value of wx_msg.wx_id
     *
     * @mbg.generated
     */
    public String getWxId() {
        return wxId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_msg.wx_id
     *
     * @param wxId the value for wx_msg.wx_id
     *
     * @mbg.generated
     */
    public void setWxId(String wxId) {
        this.wxId = wxId == null ? null : wxId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_msg.wx_group_id
     *
     * @return the value of wx_msg.wx_group_id
     *
     * @mbg.generated
     */
    public String getWxGroupId() {
        return wxGroupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_msg.wx_group_id
     *
     * @param wxGroupId the value for wx_msg.wx_group_id
     *
     * @mbg.generated
     */
    public void setWxGroupId(String wxGroupId) {
        this.wxGroupId = wxGroupId == null ? null : wxGroupId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_msg.msg_image_uri
     *
     * @return the value of wx_msg.msg_image_uri
     *
     * @mbg.generated
     */
    public String getMsgImageUri() {
        return msgImageUri;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_msg.msg_image_uri
     *
     * @param msgImageUri the value for wx_msg.msg_image_uri
     *
     * @mbg.generated
     */
    public void setMsgImageUri(String msgImageUri) {
        this.msgImageUri = msgImageUri == null ? null : msgImageUri.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_msg.msg_text
     *
     * @return the value of wx_msg.msg_text
     *
     * @mbg.generated
     */
    public String getMsgText() {
        return msgText;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_msg.msg_text
     *
     * @param msgText the value for wx_msg.msg_text
     *
     * @mbg.generated
     */
    public void setMsgText(String msgText) {
        this.msgText = msgText == null ? null : msgText.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_msg.msg_type
     *
     * @return the value of wx_msg.msg_type
     *
     * @mbg.generated
     */
    public String getMsgType() {
        return msgType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_msg.msg_type
     *
     * @param msgType the value for wx_msg.msg_type
     *
     * @mbg.generated
     */
    public void setMsgType(String msgType) {
        this.msgType = msgType == null ? null : msgType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_msg.fans_type
     *
     * @return the value of wx_msg.fans_type
     *
     * @mbg.generated
     */
    public String getFansType() {
        return fansType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_msg.fans_type
     *
     * @param fansType the value for wx_msg.fans_type
     *
     * @mbg.generated
     */
    public void setFansType(String fansType) {
        this.fansType = fansType == null ? null : fansType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_msg.msg_direct
     *
     * @return the value of wx_msg.msg_direct
     *
     * @mbg.generated
     */
    public Boolean getMsgDirect() {
        return msgDirect;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_msg.msg_direct
     *
     * @param msgDirect the value for wx_msg.msg_direct
     *
     * @mbg.generated
     */
    public void setMsgDirect(Boolean msgDirect) {
        this.msgDirect = msgDirect;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_msg.msg_platform
     *
     * @return the value of wx_msg.msg_platform
     *
     * @mbg.generated
     */
    public Boolean getMsgPlatform() {
        return msgPlatform;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_msg.msg_platform
     *
     * @param msgPlatform the value for wx_msg.msg_platform
     *
     * @mbg.generated
     */
    public void setMsgPlatform(Boolean msgPlatform) {
        this.msgPlatform = msgPlatform;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_msg.micro_serivce
     *
     * @return the value of wx_msg.micro_serivce
     *
     * @mbg.generated
     */
    public String getMicroSerivce() {
        return microSerivce;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_msg.micro_serivce
     *
     * @param microSerivce the value for wx_msg.micro_serivce
     *
     * @mbg.generated
     */
    public void setMicroSerivce(String microSerivce) {
        this.microSerivce = microSerivce == null ? null : microSerivce.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_msg.status
     *
     * @return the value of wx_msg.status
     *
     * @mbg.generated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_msg.status
     *
     * @param status the value for wx_msg.status
     *
     * @mbg.generated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_msg.receive_time
     *
     * @return the value of wx_msg.receive_time
     *
     * @mbg.generated
     */
    public Date getReceiveTime() {
        return receiveTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_msg.receive_time
     *
     * @param receiveTime the value for wx_msg.receive_time
     *
     * @mbg.generated
     */
    public void setReceiveTime(Date receiveTime) {
        this.receiveTime = receiveTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_msg.send_time
     *
     * @return the value of wx_msg.send_time
     *
     * @mbg.generated
     */
    public Date getSendTime() {
        return sendTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_msg.send_time
     *
     * @param sendTime the value for wx_msg.send_time
     *
     * @mbg.generated
     */
    public void setSendTime(Date sendTime) {
        this.sendTime = sendTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_msg.create_time
     *
     * @return the value of wx_msg.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_msg.create_time
     *
     * @param createTime the value for wx_msg.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_msg
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", wxUinId=").append(wxUinId);
        sb.append(", comId=").append(comId);
        sb.append(", wxId=").append(wxId);
        sb.append(", wxGroupId=").append(wxGroupId);
        sb.append(", msgImageUri=").append(msgImageUri);
        sb.append(", msgText=").append(msgText);
        sb.append(", msgType=").append(msgType);
        sb.append(", fansType=").append(fansType);
        sb.append(", msgDirect=").append(msgDirect);
        sb.append(", msgPlatform=").append(msgPlatform);
        sb.append(", microSerivce=").append(microSerivce);
        sb.append(", status=").append(status);
        sb.append(", receiveTime=").append(receiveTime);
        sb.append(", sendTime=").append(sendTime);
        sb.append(", createTime=").append(createTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}