package com.geeker.marketing.dao.micro.generator.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class WxMsgExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table wx_msg
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table wx_msg
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table wx_msg
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_msg
     *
     * @mbg.generated
     */
    public WxMsgExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_msg
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_msg
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_msg
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_msg
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_msg
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_msg
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_msg
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_msg
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_msg
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_msg
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table wx_msg
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andWxUinIdIsNull() {
            addCriterion("wx_uin_id is null");
            return (Criteria) this;
        }

        public Criteria andWxUinIdIsNotNull() {
            addCriterion("wx_uin_id is not null");
            return (Criteria) this;
        }

        public Criteria andWxUinIdEqualTo(String value) {
            addCriterion("wx_uin_id =", value, "wxUinId");
            return (Criteria) this;
        }

        public Criteria andWxUinIdNotEqualTo(String value) {
            addCriterion("wx_uin_id <>", value, "wxUinId");
            return (Criteria) this;
        }

        public Criteria andWxUinIdGreaterThan(String value) {
            addCriterion("wx_uin_id >", value, "wxUinId");
            return (Criteria) this;
        }

        public Criteria andWxUinIdGreaterThanOrEqualTo(String value) {
            addCriterion("wx_uin_id >=", value, "wxUinId");
            return (Criteria) this;
        }

        public Criteria andWxUinIdLessThan(String value) {
            addCriterion("wx_uin_id <", value, "wxUinId");
            return (Criteria) this;
        }

        public Criteria andWxUinIdLessThanOrEqualTo(String value) {
            addCriterion("wx_uin_id <=", value, "wxUinId");
            return (Criteria) this;
        }

        public Criteria andWxUinIdLike(String value) {
            addCriterion("wx_uin_id like", value, "wxUinId");
            return (Criteria) this;
        }

        public Criteria andWxUinIdNotLike(String value) {
            addCriterion("wx_uin_id not like", value, "wxUinId");
            return (Criteria) this;
        }

        public Criteria andWxUinIdIn(List<String> values) {
            addCriterion("wx_uin_id in", values, "wxUinId");
            return (Criteria) this;
        }

        public Criteria andWxUinIdNotIn(List<String> values) {
            addCriterion("wx_uin_id not in", values, "wxUinId");
            return (Criteria) this;
        }

        public Criteria andWxUinIdBetween(String value1, String value2) {
            addCriterion("wx_uin_id between", value1, value2, "wxUinId");
            return (Criteria) this;
        }

        public Criteria andWxUinIdNotBetween(String value1, String value2) {
            addCriterion("wx_uin_id not between", value1, value2, "wxUinId");
            return (Criteria) this;
        }

        public Criteria andComIdIsNull() {
            addCriterion("com_id is null");
            return (Criteria) this;
        }

        public Criteria andComIdIsNotNull() {
            addCriterion("com_id is not null");
            return (Criteria) this;
        }

        public Criteria andComIdEqualTo(Integer value) {
            addCriterion("com_id =", value, "comId");
            return (Criteria) this;
        }

        public Criteria andComIdNotEqualTo(Integer value) {
            addCriterion("com_id <>", value, "comId");
            return (Criteria) this;
        }

        public Criteria andComIdGreaterThan(Integer value) {
            addCriterion("com_id >", value, "comId");
            return (Criteria) this;
        }

        public Criteria andComIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("com_id >=", value, "comId");
            return (Criteria) this;
        }

        public Criteria andComIdLessThan(Integer value) {
            addCriterion("com_id <", value, "comId");
            return (Criteria) this;
        }

        public Criteria andComIdLessThanOrEqualTo(Integer value) {
            addCriterion("com_id <=", value, "comId");
            return (Criteria) this;
        }

        public Criteria andComIdIn(List<Integer> values) {
            addCriterion("com_id in", values, "comId");
            return (Criteria) this;
        }

        public Criteria andComIdNotIn(List<Integer> values) {
            addCriterion("com_id not in", values, "comId");
            return (Criteria) this;
        }

        public Criteria andComIdBetween(Integer value1, Integer value2) {
            addCriterion("com_id between", value1, value2, "comId");
            return (Criteria) this;
        }

        public Criteria andComIdNotBetween(Integer value1, Integer value2) {
            addCriterion("com_id not between", value1, value2, "comId");
            return (Criteria) this;
        }

        public Criteria andWxIdIsNull() {
            addCriterion("wx_id is null");
            return (Criteria) this;
        }

        public Criteria andWxIdIsNotNull() {
            addCriterion("wx_id is not null");
            return (Criteria) this;
        }

        public Criteria andWxIdEqualTo(String value) {
            addCriterion("wx_id =", value, "wxId");
            return (Criteria) this;
        }

        public Criteria andWxIdNotEqualTo(String value) {
            addCriterion("wx_id <>", value, "wxId");
            return (Criteria) this;
        }

        public Criteria andWxIdGreaterThan(String value) {
            addCriterion("wx_id >", value, "wxId");
            return (Criteria) this;
        }

        public Criteria andWxIdGreaterThanOrEqualTo(String value) {
            addCriterion("wx_id >=", value, "wxId");
            return (Criteria) this;
        }

        public Criteria andWxIdLessThan(String value) {
            addCriterion("wx_id <", value, "wxId");
            return (Criteria) this;
        }

        public Criteria andWxIdLessThanOrEqualTo(String value) {
            addCriterion("wx_id <=", value, "wxId");
            return (Criteria) this;
        }

        public Criteria andWxIdLike(String value) {
            addCriterion("wx_id like", value, "wxId");
            return (Criteria) this;
        }

        public Criteria andWxIdNotLike(String value) {
            addCriterion("wx_id not like", value, "wxId");
            return (Criteria) this;
        }

        public Criteria andWxIdIn(List<String> values) {
            addCriterion("wx_id in", values, "wxId");
            return (Criteria) this;
        }

        public Criteria andWxIdNotIn(List<String> values) {
            addCriterion("wx_id not in", values, "wxId");
            return (Criteria) this;
        }

        public Criteria andWxIdBetween(String value1, String value2) {
            addCriterion("wx_id between", value1, value2, "wxId");
            return (Criteria) this;
        }

        public Criteria andWxIdNotBetween(String value1, String value2) {
            addCriterion("wx_id not between", value1, value2, "wxId");
            return (Criteria) this;
        }

        public Criteria andWxGroupIdIsNull() {
            addCriterion("wx_group_id is null");
            return (Criteria) this;
        }

        public Criteria andWxGroupIdIsNotNull() {
            addCriterion("wx_group_id is not null");
            return (Criteria) this;
        }

        public Criteria andWxGroupIdEqualTo(String value) {
            addCriterion("wx_group_id =", value, "wxGroupId");
            return (Criteria) this;
        }

        public Criteria andWxGroupIdNotEqualTo(String value) {
            addCriterion("wx_group_id <>", value, "wxGroupId");
            return (Criteria) this;
        }

        public Criteria andWxGroupIdGreaterThan(String value) {
            addCriterion("wx_group_id >", value, "wxGroupId");
            return (Criteria) this;
        }

        public Criteria andWxGroupIdGreaterThanOrEqualTo(String value) {
            addCriterion("wx_group_id >=", value, "wxGroupId");
            return (Criteria) this;
        }

        public Criteria andWxGroupIdLessThan(String value) {
            addCriterion("wx_group_id <", value, "wxGroupId");
            return (Criteria) this;
        }

        public Criteria andWxGroupIdLessThanOrEqualTo(String value) {
            addCriterion("wx_group_id <=", value, "wxGroupId");
            return (Criteria) this;
        }

        public Criteria andWxGroupIdLike(String value) {
            addCriterion("wx_group_id like", value, "wxGroupId");
            return (Criteria) this;
        }

        public Criteria andWxGroupIdNotLike(String value) {
            addCriterion("wx_group_id not like", value, "wxGroupId");
            return (Criteria) this;
        }

        public Criteria andWxGroupIdIn(List<String> values) {
            addCriterion("wx_group_id in", values, "wxGroupId");
            return (Criteria) this;
        }

        public Criteria andWxGroupIdNotIn(List<String> values) {
            addCriterion("wx_group_id not in", values, "wxGroupId");
            return (Criteria) this;
        }

        public Criteria andWxGroupIdBetween(String value1, String value2) {
            addCriterion("wx_group_id between", value1, value2, "wxGroupId");
            return (Criteria) this;
        }

        public Criteria andWxGroupIdNotBetween(String value1, String value2) {
            addCriterion("wx_group_id not between", value1, value2, "wxGroupId");
            return (Criteria) this;
        }

        public Criteria andMsgImageUriIsNull() {
            addCriterion("msg_image_uri is null");
            return (Criteria) this;
        }

        public Criteria andMsgImageUriIsNotNull() {
            addCriterion("msg_image_uri is not null");
            return (Criteria) this;
        }

        public Criteria andMsgImageUriEqualTo(String value) {
            addCriterion("msg_image_uri =", value, "msgImageUri");
            return (Criteria) this;
        }

        public Criteria andMsgImageUriNotEqualTo(String value) {
            addCriterion("msg_image_uri <>", value, "msgImageUri");
            return (Criteria) this;
        }

        public Criteria andMsgImageUriGreaterThan(String value) {
            addCriterion("msg_image_uri >", value, "msgImageUri");
            return (Criteria) this;
        }

        public Criteria andMsgImageUriGreaterThanOrEqualTo(String value) {
            addCriterion("msg_image_uri >=", value, "msgImageUri");
            return (Criteria) this;
        }

        public Criteria andMsgImageUriLessThan(String value) {
            addCriterion("msg_image_uri <", value, "msgImageUri");
            return (Criteria) this;
        }

        public Criteria andMsgImageUriLessThanOrEqualTo(String value) {
            addCriterion("msg_image_uri <=", value, "msgImageUri");
            return (Criteria) this;
        }

        public Criteria andMsgImageUriLike(String value) {
            addCriterion("msg_image_uri like", value, "msgImageUri");
            return (Criteria) this;
        }

        public Criteria andMsgImageUriNotLike(String value) {
            addCriterion("msg_image_uri not like", value, "msgImageUri");
            return (Criteria) this;
        }

        public Criteria andMsgImageUriIn(List<String> values) {
            addCriterion("msg_image_uri in", values, "msgImageUri");
            return (Criteria) this;
        }

        public Criteria andMsgImageUriNotIn(List<String> values) {
            addCriterion("msg_image_uri not in", values, "msgImageUri");
            return (Criteria) this;
        }

        public Criteria andMsgImageUriBetween(String value1, String value2) {
            addCriterion("msg_image_uri between", value1, value2, "msgImageUri");
            return (Criteria) this;
        }

        public Criteria andMsgImageUriNotBetween(String value1, String value2) {
            addCriterion("msg_image_uri not between", value1, value2, "msgImageUri");
            return (Criteria) this;
        }

        public Criteria andMsgTextIsNull() {
            addCriterion("msg_text is null");
            return (Criteria) this;
        }

        public Criteria andMsgTextIsNotNull() {
            addCriterion("msg_text is not null");
            return (Criteria) this;
        }

        public Criteria andMsgTextEqualTo(String value) {
            addCriterion("msg_text =", value, "msgText");
            return (Criteria) this;
        }

        public Criteria andMsgTextNotEqualTo(String value) {
            addCriterion("msg_text <>", value, "msgText");
            return (Criteria) this;
        }

        public Criteria andMsgTextGreaterThan(String value) {
            addCriterion("msg_text >", value, "msgText");
            return (Criteria) this;
        }

        public Criteria andMsgTextGreaterThanOrEqualTo(String value) {
            addCriterion("msg_text >=", value, "msgText");
            return (Criteria) this;
        }

        public Criteria andMsgTextLessThan(String value) {
            addCriterion("msg_text <", value, "msgText");
            return (Criteria) this;
        }

        public Criteria andMsgTextLessThanOrEqualTo(String value) {
            addCriterion("msg_text <=", value, "msgText");
            return (Criteria) this;
        }

        public Criteria andMsgTextLike(String value) {
            addCriterion("msg_text like", value, "msgText");
            return (Criteria) this;
        }

        public Criteria andMsgTextNotLike(String value) {
            addCriterion("msg_text not like", value, "msgText");
            return (Criteria) this;
        }

        public Criteria andMsgTextIn(List<String> values) {
            addCriterion("msg_text in", values, "msgText");
            return (Criteria) this;
        }

        public Criteria andMsgTextNotIn(List<String> values) {
            addCriterion("msg_text not in", values, "msgText");
            return (Criteria) this;
        }

        public Criteria andMsgTextBetween(String value1, String value2) {
            addCriterion("msg_text between", value1, value2, "msgText");
            return (Criteria) this;
        }

        public Criteria andMsgTextNotBetween(String value1, String value2) {
            addCriterion("msg_text not between", value1, value2, "msgText");
            return (Criteria) this;
        }

        public Criteria andMsgTypeIsNull() {
            addCriterion("msg_type is null");
            return (Criteria) this;
        }

        public Criteria andMsgTypeIsNotNull() {
            addCriterion("msg_type is not null");
            return (Criteria) this;
        }

        public Criteria andMsgTypeEqualTo(String value) {
            addCriterion("msg_type =", value, "msgType");
            return (Criteria) this;
        }

        public Criteria andMsgTypeNotEqualTo(String value) {
            addCriterion("msg_type <>", value, "msgType");
            return (Criteria) this;
        }

        public Criteria andMsgTypeGreaterThan(String value) {
            addCriterion("msg_type >", value, "msgType");
            return (Criteria) this;
        }

        public Criteria andMsgTypeGreaterThanOrEqualTo(String value) {
            addCriterion("msg_type >=", value, "msgType");
            return (Criteria) this;
        }

        public Criteria andMsgTypeLessThan(String value) {
            addCriterion("msg_type <", value, "msgType");
            return (Criteria) this;
        }

        public Criteria andMsgTypeLessThanOrEqualTo(String value) {
            addCriterion("msg_type <=", value, "msgType");
            return (Criteria) this;
        }

        public Criteria andMsgTypeLike(String value) {
            addCriterion("msg_type like", value, "msgType");
            return (Criteria) this;
        }

        public Criteria andMsgTypeNotLike(String value) {
            addCriterion("msg_type not like", value, "msgType");
            return (Criteria) this;
        }

        public Criteria andMsgTypeIn(List<String> values) {
            addCriterion("msg_type in", values, "msgType");
            return (Criteria) this;
        }

        public Criteria andMsgTypeNotIn(List<String> values) {
            addCriterion("msg_type not in", values, "msgType");
            return (Criteria) this;
        }

        public Criteria andMsgTypeBetween(String value1, String value2) {
            addCriterion("msg_type between", value1, value2, "msgType");
            return (Criteria) this;
        }

        public Criteria andMsgTypeNotBetween(String value1, String value2) {
            addCriterion("msg_type not between", value1, value2, "msgType");
            return (Criteria) this;
        }

        public Criteria andFansTypeIsNull() {
            addCriterion("fans_type is null");
            return (Criteria) this;
        }

        public Criteria andFansTypeIsNotNull() {
            addCriterion("fans_type is not null");
            return (Criteria) this;
        }

        public Criteria andFansTypeEqualTo(String value) {
            addCriterion("fans_type =", value, "fansType");
            return (Criteria) this;
        }

        public Criteria andFansTypeNotEqualTo(String value) {
            addCriterion("fans_type <>", value, "fansType");
            return (Criteria) this;
        }

        public Criteria andFansTypeGreaterThan(String value) {
            addCriterion("fans_type >", value, "fansType");
            return (Criteria) this;
        }

        public Criteria andFansTypeGreaterThanOrEqualTo(String value) {
            addCriterion("fans_type >=", value, "fansType");
            return (Criteria) this;
        }

        public Criteria andFansTypeLessThan(String value) {
            addCriterion("fans_type <", value, "fansType");
            return (Criteria) this;
        }

        public Criteria andFansTypeLessThanOrEqualTo(String value) {
            addCriterion("fans_type <=", value, "fansType");
            return (Criteria) this;
        }

        public Criteria andFansTypeLike(String value) {
            addCriterion("fans_type like", value, "fansType");
            return (Criteria) this;
        }

        public Criteria andFansTypeNotLike(String value) {
            addCriterion("fans_type not like", value, "fansType");
            return (Criteria) this;
        }

        public Criteria andFansTypeIn(List<String> values) {
            addCriterion("fans_type in", values, "fansType");
            return (Criteria) this;
        }

        public Criteria andFansTypeNotIn(List<String> values) {
            addCriterion("fans_type not in", values, "fansType");
            return (Criteria) this;
        }

        public Criteria andFansTypeBetween(String value1, String value2) {
            addCriterion("fans_type between", value1, value2, "fansType");
            return (Criteria) this;
        }

        public Criteria andFansTypeNotBetween(String value1, String value2) {
            addCriterion("fans_type not between", value1, value2, "fansType");
            return (Criteria) this;
        }

        public Criteria andMsgDirectIsNull() {
            addCriterion("msg_direct is null");
            return (Criteria) this;
        }

        public Criteria andMsgDirectIsNotNull() {
            addCriterion("msg_direct is not null");
            return (Criteria) this;
        }

        public Criteria andMsgDirectEqualTo(Boolean value) {
            addCriterion("msg_direct =", value, "msgDirect");
            return (Criteria) this;
        }

        public Criteria andMsgDirectNotEqualTo(Boolean value) {
            addCriterion("msg_direct <>", value, "msgDirect");
            return (Criteria) this;
        }

        public Criteria andMsgDirectGreaterThan(Boolean value) {
            addCriterion("msg_direct >", value, "msgDirect");
            return (Criteria) this;
        }

        public Criteria andMsgDirectGreaterThanOrEqualTo(Boolean value) {
            addCriterion("msg_direct >=", value, "msgDirect");
            return (Criteria) this;
        }

        public Criteria andMsgDirectLessThan(Boolean value) {
            addCriterion("msg_direct <", value, "msgDirect");
            return (Criteria) this;
        }

        public Criteria andMsgDirectLessThanOrEqualTo(Boolean value) {
            addCriterion("msg_direct <=", value, "msgDirect");
            return (Criteria) this;
        }

        public Criteria andMsgDirectIn(List<Boolean> values) {
            addCriterion("msg_direct in", values, "msgDirect");
            return (Criteria) this;
        }

        public Criteria andMsgDirectNotIn(List<Boolean> values) {
            addCriterion("msg_direct not in", values, "msgDirect");
            return (Criteria) this;
        }

        public Criteria andMsgDirectBetween(Boolean value1, Boolean value2) {
            addCriterion("msg_direct between", value1, value2, "msgDirect");
            return (Criteria) this;
        }

        public Criteria andMsgDirectNotBetween(Boolean value1, Boolean value2) {
            addCriterion("msg_direct not between", value1, value2, "msgDirect");
            return (Criteria) this;
        }

        public Criteria andMsgPlatformIsNull() {
            addCriterion("msg_platform is null");
            return (Criteria) this;
        }

        public Criteria andMsgPlatformIsNotNull() {
            addCriterion("msg_platform is not null");
            return (Criteria) this;
        }

        public Criteria andMsgPlatformEqualTo(Boolean value) {
            addCriterion("msg_platform =", value, "msgPlatform");
            return (Criteria) this;
        }

        public Criteria andMsgPlatformNotEqualTo(Boolean value) {
            addCriterion("msg_platform <>", value, "msgPlatform");
            return (Criteria) this;
        }

        public Criteria andMsgPlatformGreaterThan(Boolean value) {
            addCriterion("msg_platform >", value, "msgPlatform");
            return (Criteria) this;
        }

        public Criteria andMsgPlatformGreaterThanOrEqualTo(Boolean value) {
            addCriterion("msg_platform >=", value, "msgPlatform");
            return (Criteria) this;
        }

        public Criteria andMsgPlatformLessThan(Boolean value) {
            addCriterion("msg_platform <", value, "msgPlatform");
            return (Criteria) this;
        }

        public Criteria andMsgPlatformLessThanOrEqualTo(Boolean value) {
            addCriterion("msg_platform <=", value, "msgPlatform");
            return (Criteria) this;
        }

        public Criteria andMsgPlatformIn(List<Boolean> values) {
            addCriterion("msg_platform in", values, "msgPlatform");
            return (Criteria) this;
        }

        public Criteria andMsgPlatformNotIn(List<Boolean> values) {
            addCriterion("msg_platform not in", values, "msgPlatform");
            return (Criteria) this;
        }

        public Criteria andMsgPlatformBetween(Boolean value1, Boolean value2) {
            addCriterion("msg_platform between", value1, value2, "msgPlatform");
            return (Criteria) this;
        }

        public Criteria andMsgPlatformNotBetween(Boolean value1, Boolean value2) {
            addCriterion("msg_platform not between", value1, value2, "msgPlatform");
            return (Criteria) this;
        }

        public Criteria andMicroSerivceIsNull() {
            addCriterion("micro_serivce is null");
            return (Criteria) this;
        }

        public Criteria andMicroSerivceIsNotNull() {
            addCriterion("micro_serivce is not null");
            return (Criteria) this;
        }

        public Criteria andMicroSerivceEqualTo(String value) {
            addCriterion("micro_serivce =", value, "microSerivce");
            return (Criteria) this;
        }

        public Criteria andMicroSerivceNotEqualTo(String value) {
            addCriterion("micro_serivce <>", value, "microSerivce");
            return (Criteria) this;
        }

        public Criteria andMicroSerivceGreaterThan(String value) {
            addCriterion("micro_serivce >", value, "microSerivce");
            return (Criteria) this;
        }

        public Criteria andMicroSerivceGreaterThanOrEqualTo(String value) {
            addCriterion("micro_serivce >=", value, "microSerivce");
            return (Criteria) this;
        }

        public Criteria andMicroSerivceLessThan(String value) {
            addCriterion("micro_serivce <", value, "microSerivce");
            return (Criteria) this;
        }

        public Criteria andMicroSerivceLessThanOrEqualTo(String value) {
            addCriterion("micro_serivce <=", value, "microSerivce");
            return (Criteria) this;
        }

        public Criteria andMicroSerivceLike(String value) {
            addCriterion("micro_serivce like", value, "microSerivce");
            return (Criteria) this;
        }

        public Criteria andMicroSerivceNotLike(String value) {
            addCriterion("micro_serivce not like", value, "microSerivce");
            return (Criteria) this;
        }

        public Criteria andMicroSerivceIn(List<String> values) {
            addCriterion("micro_serivce in", values, "microSerivce");
            return (Criteria) this;
        }

        public Criteria andMicroSerivceNotIn(List<String> values) {
            addCriterion("micro_serivce not in", values, "microSerivce");
            return (Criteria) this;
        }

        public Criteria andMicroSerivceBetween(String value1, String value2) {
            addCriterion("micro_serivce between", value1, value2, "microSerivce");
            return (Criteria) this;
        }

        public Criteria andMicroSerivceNotBetween(String value1, String value2) {
            addCriterion("micro_serivce not between", value1, value2, "microSerivce");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(Integer value) {
            addCriterion("status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(Integer value) {
            addCriterion("status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(Integer value) {
            addCriterion("status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(Integer value) {
            addCriterion("status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(Integer value) {
            addCriterion("status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<Integer> values) {
            addCriterion("status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<Integer> values) {
            addCriterion("status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(Integer value1, Integer value2) {
            addCriterion("status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("status not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andReceiveTimeIsNull() {
            addCriterion("receive_time is null");
            return (Criteria) this;
        }

        public Criteria andReceiveTimeIsNotNull() {
            addCriterion("receive_time is not null");
            return (Criteria) this;
        }

        public Criteria andReceiveTimeEqualTo(Date value) {
            addCriterion("receive_time =", value, "receiveTime");
            return (Criteria) this;
        }

        public Criteria andReceiveTimeNotEqualTo(Date value) {
            addCriterion("receive_time <>", value, "receiveTime");
            return (Criteria) this;
        }

        public Criteria andReceiveTimeGreaterThan(Date value) {
            addCriterion("receive_time >", value, "receiveTime");
            return (Criteria) this;
        }

        public Criteria andReceiveTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("receive_time >=", value, "receiveTime");
            return (Criteria) this;
        }

        public Criteria andReceiveTimeLessThan(Date value) {
            addCriterion("receive_time <", value, "receiveTime");
            return (Criteria) this;
        }

        public Criteria andReceiveTimeLessThanOrEqualTo(Date value) {
            addCriterion("receive_time <=", value, "receiveTime");
            return (Criteria) this;
        }

        public Criteria andReceiveTimeIn(List<Date> values) {
            addCriterion("receive_time in", values, "receiveTime");
            return (Criteria) this;
        }

        public Criteria andReceiveTimeNotIn(List<Date> values) {
            addCriterion("receive_time not in", values, "receiveTime");
            return (Criteria) this;
        }

        public Criteria andReceiveTimeBetween(Date value1, Date value2) {
            addCriterion("receive_time between", value1, value2, "receiveTime");
            return (Criteria) this;
        }

        public Criteria andReceiveTimeNotBetween(Date value1, Date value2) {
            addCriterion("receive_time not between", value1, value2, "receiveTime");
            return (Criteria) this;
        }

        public Criteria andSendTimeIsNull() {
            addCriterion("send_time is null");
            return (Criteria) this;
        }

        public Criteria andSendTimeIsNotNull() {
            addCriterion("send_time is not null");
            return (Criteria) this;
        }

        public Criteria andSendTimeEqualTo(Date value) {
            addCriterion("send_time =", value, "sendTime");
            return (Criteria) this;
        }

        public Criteria andSendTimeNotEqualTo(Date value) {
            addCriterion("send_time <>", value, "sendTime");
            return (Criteria) this;
        }

        public Criteria andSendTimeGreaterThan(Date value) {
            addCriterion("send_time >", value, "sendTime");
            return (Criteria) this;
        }

        public Criteria andSendTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("send_time >=", value, "sendTime");
            return (Criteria) this;
        }

        public Criteria andSendTimeLessThan(Date value) {
            addCriterion("send_time <", value, "sendTime");
            return (Criteria) this;
        }

        public Criteria andSendTimeLessThanOrEqualTo(Date value) {
            addCriterion("send_time <=", value, "sendTime");
            return (Criteria) this;
        }

        public Criteria andSendTimeIn(List<Date> values) {
            addCriterion("send_time in", values, "sendTime");
            return (Criteria) this;
        }

        public Criteria andSendTimeNotIn(List<Date> values) {
            addCriterion("send_time not in", values, "sendTime");
            return (Criteria) this;
        }

        public Criteria andSendTimeBetween(Date value1, Date value2) {
            addCriterion("send_time between", value1, value2, "sendTime");
            return (Criteria) this;
        }

        public Criteria andSendTimeNotBetween(Date value1, Date value2) {
            addCriterion("send_time not between", value1, value2, "sendTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table wx_msg
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table wx_msg
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}