package com.geeker.marketing.dao.micro.generator.mapper;

import com.geeker.marketing.dao.micro.generator.model.MicroDevice;
import com.geeker.marketing.dao.micro.generator.model.MicroDeviceExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface MicroDeviceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table micro_device
     *
     * @mbg.generated
     */
    long countByExample(MicroDeviceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table micro_device
     *
     * @mbg.generated
     */
    int deleteByExample(MicroDeviceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table micro_device
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table micro_device
     *
     * @mbg.generated
     */
    int insert(MicroDevice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table micro_device
     *
     * @mbg.generated
     */
    int insertSelective(MicroDevice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table micro_device
     *
     * @mbg.generated
     */
    List<MicroDevice> selectByExampleWithRowbounds(MicroDeviceExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table micro_device
     *
     * @mbg.generated
     */
    List<MicroDevice> selectByExample(MicroDeviceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table micro_device
     *
     * @mbg.generated
     */
    MicroDevice selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table micro_device
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") MicroDevice record, @Param("example") MicroDeviceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table micro_device
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") MicroDevice record, @Param("example") MicroDeviceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table micro_device
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(MicroDevice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table micro_device
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(MicroDevice record);
}