package com.geeker.marketing.dao.micro.generator.mapper;

import com.geeker.marketing.dao.micro.generator.model.OpConnectPool;
import com.geeker.marketing.dao.micro.generator.model.OpConnectPoolExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface OpConnectPoolMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table op_connect_pool
     *
     * @mbg.generated
     */
    long countByExample(OpConnectPoolExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table op_connect_pool
     *
     * @mbg.generated
     */
    int deleteByExample(OpConnectPoolExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table op_connect_pool
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table op_connect_pool
     *
     * @mbg.generated
     */
    int insert(OpConnectPool record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table op_connect_pool
     *
     * @mbg.generated
     */
    int insertSelective(OpConnectPool record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table op_connect_pool
     *
     * @mbg.generated
     */
    List<OpConnectPool> selectByExampleWithRowbounds(OpConnectPoolExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table op_connect_pool
     *
     * @mbg.generated
     */
    List<OpConnectPool> selectByExample(OpConnectPoolExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table op_connect_pool
     *
     * @mbg.generated
     */
    OpConnectPool selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table op_connect_pool
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") OpConnectPool record, @Param("example") OpConnectPoolExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table op_connect_pool
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") OpConnectPool record, @Param("example") OpConnectPoolExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table op_connect_pool
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(OpConnectPool record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table op_connect_pool
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(OpConnectPool record);
}