package com.geeker.marketing.dao.micro.generator.mapper;

import com.geeker.marketing.dao.micro.generator.model.OpDeviceReport;
import com.geeker.marketing.dao.micro.generator.model.OpDeviceReportExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface OpDeviceReportMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table op_device_report
     *
     * @mbg.generated
     */
    long countByExample(OpDeviceReportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table op_device_report
     *
     * @mbg.generated
     */
    int deleteByExample(OpDeviceReportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table op_device_report
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table op_device_report
     *
     * @mbg.generated
     */
    int insert(OpDeviceReport record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table op_device_report
     *
     * @mbg.generated
     */
    int insertSelective(OpDeviceReport record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table op_device_report
     *
     * @mbg.generated
     */
    List<OpDeviceReport> selectByExampleWithRowbounds(OpDeviceReportExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table op_device_report
     *
     * @mbg.generated
     */
    List<OpDeviceReport> selectByExample(OpDeviceReportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table op_device_report
     *
     * @mbg.generated
     */
    OpDeviceReport selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table op_device_report
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") OpDeviceReport record, @Param("example") OpDeviceReportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table op_device_report
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") OpDeviceReport record, @Param("example") OpDeviceReportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table op_device_report
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(OpDeviceReport record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table op_device_report
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(OpDeviceReport record);
}