package com.geeker.marketing.dao.micro.generator.mapper;

import com.geeker.marketing.dao.micro.generator.model.OpDeviceCmd;
import com.geeker.marketing.dao.micro.generator.model.OpDeviceCmdExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface OpDeviceCmdMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table op_device_cmd
     *
     * @mbg.generated
     */
    long countByExample(OpDeviceCmdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table op_device_cmd
     *
     * @mbg.generated
     */
    int deleteByExample(OpDeviceCmdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table op_device_cmd
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table op_device_cmd
     *
     * @mbg.generated
     */
    int insert(OpDeviceCmd record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table op_device_cmd
     *
     * @mbg.generated
     */
    int insertSelective(OpDeviceCmd record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table op_device_cmd
     *
     * @mbg.generated
     */
    List<OpDeviceCmd> selectByExampleWithRowbounds(OpDeviceCmdExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table op_device_cmd
     *
     * @mbg.generated
     */
    List<OpDeviceCmd> selectByExample(OpDeviceCmdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table op_device_cmd
     *
     * @mbg.generated
     */
    OpDeviceCmd selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table op_device_cmd
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") OpDeviceCmd record, @Param("example") OpDeviceCmdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table op_device_cmd
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") OpDeviceCmd record, @Param("example") OpDeviceCmdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table op_device_cmd
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(OpDeviceCmd record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table op_device_cmd
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(OpDeviceCmd record);
}