package com.geeker.marketing.dao.micro.generator.mapper;

import com.geeker.marketing.dao.micro.generator.model.OpDevice;
import com.geeker.marketing.dao.micro.generator.model.OpDeviceExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface OpDeviceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table op_device
     *
     * @mbg.generated
     */
    long countByExample(OpDeviceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table op_device
     *
     * @mbg.generated
     */
    int deleteByExample(OpDeviceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table op_device
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table op_device
     *
     * @mbg.generated
     */
    int insert(OpDevice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table op_device
     *
     * @mbg.generated
     */
    int insertSelective(OpDevice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table op_device
     *
     * @mbg.generated
     */
    List<OpDevice> selectByExampleWithRowbounds(OpDeviceExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table op_device
     *
     * @mbg.generated
     */
    List<OpDevice> selectByExample(OpDeviceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table op_device
     *
     * @mbg.generated
     */
    OpDevice selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table op_device
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") OpDevice record, @Param("example") OpDeviceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table op_device
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") OpDevice record, @Param("example") OpDeviceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table op_device
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(OpDevice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table op_device
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(OpDevice record);
}