package com.geeker.marketing.dao.micro.generator.mapper;

import com.geeker.marketing.dao.micro.generator.model.OpDeviceRegister;
import com.geeker.marketing.dao.micro.generator.model.OpDeviceRegisterExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface OpDeviceRegisterMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table op_device_register
     *
     * @mbg.generated
     */
    long countByExample(OpDeviceRegisterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table op_device_register
     *
     * @mbg.generated
     */
    int deleteByExample(OpDeviceRegisterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table op_device_register
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table op_device_register
     *
     * @mbg.generated
     */
    int insert(OpDeviceRegister record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table op_device_register
     *
     * @mbg.generated
     */
    int insertSelective(OpDeviceRegister record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table op_device_register
     *
     * @mbg.generated
     */
    List<OpDeviceRegister> selectByExampleWithRowbounds(OpDeviceRegisterExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table op_device_register
     *
     * @mbg.generated
     */
    List<OpDeviceRegister> selectByExample(OpDeviceRegisterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table op_device_register
     *
     * @mbg.generated
     */
    OpDeviceRegister selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table op_device_register
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") OpDeviceRegister record, @Param("example") OpDeviceRegisterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table op_device_register
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") OpDeviceRegister record, @Param("example") OpDeviceRegisterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table op_device_register
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(OpDeviceRegister record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table op_device_register
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(OpDeviceRegister record);
}