package com.geeker.marketing.dao.micro.generator.mapper;

import com.geeker.marketing.dao.micro.generator.model.SysErrorProcLog;
import com.geeker.marketing.dao.micro.generator.model.SysErrorProcLogExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface SysErrorProcLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_error_proc_log
     *
     * @mbg.generated
     */
    long countByExample(SysErrorProcLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_error_proc_log
     *
     * @mbg.generated
     */
    int deleteByExample(SysErrorProcLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_error_proc_log
     *
     * @mbg.generated
     */
    int insert(SysErrorProcLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_error_proc_log
     *
     * @mbg.generated
     */
    int insertSelective(SysErrorProcLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_error_proc_log
     *
     * @mbg.generated
     */
    List<SysErrorProcLog> selectByExampleWithRowbounds(SysErrorProcLogExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_error_proc_log
     *
     * @mbg.generated
     */
    List<SysErrorProcLog> selectByExample(SysErrorProcLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_error_proc_log
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") SysErrorProcLog record, @Param("example") SysErrorProcLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_error_proc_log
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") SysErrorProcLog record, @Param("example") SysErrorProcLogExample example);
}