package com.geeker.marketing.dao.micro.generator.mapper;

import com.geeker.marketing.dao.micro.generator.model.WxAccount;
import com.geeker.marketing.dao.micro.generator.model.WxAccountExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface WxAccountMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_account
     *
     * @mbg.generated
     */
    long countByExample(WxAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_account
     *
     * @mbg.generated
     */
    int deleteByExample(WxAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_account
     *
     * @mbg.generated
     */
    int insert(WxAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_account
     *
     * @mbg.generated
     */
    int insertSelective(WxAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_account
     *
     * @mbg.generated
     */
    List<WxAccount> selectByExampleWithRowbounds(WxAccountExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_account
     *
     * @mbg.generated
     */
    List<WxAccount> selectByExample(WxAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_account
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") WxAccount record, @Param("example") WxAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_account
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") WxAccount record, @Param("example") WxAccountExample example);
}