package com.geeker.marketing.dao.micro.generator.mapper;

import com.geeker.marketing.dao.micro.generator.model.WxEvent;
import com.geeker.marketing.dao.micro.generator.model.WxEventExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface WxEventMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_event
     *
     * @mbg.generated
     */
    long countByExample(WxEventExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_event
     *
     * @mbg.generated
     */
    int deleteByExample(WxEventExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_event
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_event
     *
     * @mbg.generated
     */
    int insert(WxEvent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_event
     *
     * @mbg.generated
     */
    int insertSelective(WxEvent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_event
     *
     * @mbg.generated
     */
    List<WxEvent> selectByExampleWithRowbounds(WxEventExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_event
     *
     * @mbg.generated
     */
    List<WxEvent> selectByExample(WxEventExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_event
     *
     * @mbg.generated
     */
    WxEvent selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_event
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") WxEvent record, @Param("example") WxEventExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_event
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") WxEvent record, @Param("example") WxEventExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_event
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(WxEvent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_event
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(WxEvent record);
}