package com.geeker.marketing.dao.micro.generator.mapper;

import com.geeker.marketing.dao.micro.generator.model.WxFans;
import com.geeker.marketing.dao.micro.generator.model.WxFansExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface WxFansMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_fans
     *
     * @mbg.generated
     */
    long countByExample(WxFansExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_fans
     *
     * @mbg.generated
     */
    int deleteByExample(WxFansExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_fans
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_fans
     *
     * @mbg.generated
     */
    int insert(WxFans record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_fans
     *
     * @mbg.generated
     */
    int insertSelective(WxFans record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_fans
     *
     * @mbg.generated
     */
    List<WxFans> selectByExampleWithRowbounds(WxFansExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_fans
     *
     * @mbg.generated
     */
    List<WxFans> selectByExample(WxFansExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_fans
     *
     * @mbg.generated
     */
    WxFans selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_fans
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") WxFans record, @Param("example") WxFansExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_fans
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") WxFans record, @Param("example") WxFansExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_fans
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(WxFans record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_fans
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(WxFans record);
}