package com.geeker.marketing.dao.micro.generator.mapper;

import com.geeker.marketing.dao.micro.generator.model.WxGroupFans;
import com.geeker.marketing.dao.micro.generator.model.WxGroupFansExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface WxGroupFansMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_group_fans
     *
     * @mbg.generated
     */
    long countByExample(WxGroupFansExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_group_fans
     *
     * @mbg.generated
     */
    int deleteByExample(WxGroupFansExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_group_fans
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_group_fans
     *
     * @mbg.generated
     */
    int insert(WxGroupFans record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_group_fans
     *
     * @mbg.generated
     */
    int insertSelective(WxGroupFans record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_group_fans
     *
     * @mbg.generated
     */
    List<WxGroupFans> selectByExampleWithRowbounds(WxGroupFansExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_group_fans
     *
     * @mbg.generated
     */
    List<WxGroupFans> selectByExample(WxGroupFansExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_group_fans
     *
     * @mbg.generated
     */
    WxGroupFans selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_group_fans
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") WxGroupFans record, @Param("example") WxGroupFansExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_group_fans
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") WxGroupFans record, @Param("example") WxGroupFansExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_group_fans
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(WxGroupFans record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_group_fans
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(WxGroupFans record);
}