package com.geeker.marketing.dao.micro.generator.mapper;

import com.geeker.marketing.dao.micro.generator.model.WxMsg;
import com.geeker.marketing.dao.micro.generator.model.WxMsgExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface WxMsgMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_msg
     *
     * @mbg.generated
     */
    long countByExample(WxMsgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_msg
     *
     * @mbg.generated
     */
    int deleteByExample(WxMsgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_msg
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_msg
     *
     * @mbg.generated
     */
    int insert(WxMsg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_msg
     *
     * @mbg.generated
     */
    int insertSelective(WxMsg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_msg
     *
     * @mbg.generated
     */
    List<WxMsg> selectByExampleWithRowbounds(WxMsgExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_msg
     *
     * @mbg.generated
     */
    List<WxMsg> selectByExample(WxMsgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_msg
     *
     * @mbg.generated
     */
    WxMsg selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_msg
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") WxMsg record, @Param("example") WxMsgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_msg
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") WxMsg record, @Param("example") WxMsgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_msg
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(WxMsg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_msg
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(WxMsg record);
}