package com.geeker.marketing.dao.geeker.generator.model;

import java.io.Serializable;
import java.util.Date;

public class User implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.company_id
     *
     * @mbg.generated
     */
    private Integer companyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.login_name
     *
     * @mbg.generated
     */
    private String loginName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.login_pwd
     *
     * @mbg.generated
     */
    private String loginPwd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_name
     *
     * @mbg.generated
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.sex
     *
     * @mbg.generated
     */
    private String sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.mobile
     *
     * @mbg.generated
     */
    private String mobile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.is_mobile_valid
     *
     * @mbg.generated
     */
    private Boolean isMobileValid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.email
     *
     * @mbg.generated
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.is_email_valid
     *
     * @mbg.generated
     */
    private Boolean isEmailValid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.STATUS
     *
     * @mbg.generated
     */
    private Boolean status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.qq
     *
     * @mbg.generated
     */
    private String qq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.last_login_time
     *
     * @mbg.generated
     */
    private Date lastLoginTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.weixin_id
     *
     * @mbg.generated
     */
    private String weixinId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.job
     *
     * @mbg.generated
     */
    private String job;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.head_name
     *
     * @mbg.generated
     */
    private String headName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.birthday
     *
     * @mbg.generated
     */
    private Date birthday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.upper_Id
     *
     * @mbg.generated
     */
    private Integer upperId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.pass_code
     *
     * @mbg.generated
     */
    private Integer passCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.is_admin
     *
     * @mbg.generated
     */
    private Boolean isAdmin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.is_agree_disclaimer
     *
     * @mbg.generated
     */
    private Boolean isAgreeDisclaimer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.agree_disclaimer_time
     *
     * @mbg.generated
     */
    private Date agreeDisclaimerTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.pwd_update_time
     *
     * @mbg.generated
     */
    private Date pwdUpdateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.id
     *
     * @return the value of user.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.id
     *
     * @param id the value for user.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.company_id
     *
     * @return the value of user.company_id
     *
     * @mbg.generated
     */
    public Integer getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.company_id
     *
     * @param companyId the value for user.company_id
     *
     * @mbg.generated
     */
    public void setCompanyId(Integer companyId) {
        this.companyId = companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.login_name
     *
     * @return the value of user.login_name
     *
     * @mbg.generated
     */
    public String getLoginName() {
        return loginName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.login_name
     *
     * @param loginName the value for user.login_name
     *
     * @mbg.generated
     */
    public void setLoginName(String loginName) {
        this.loginName = loginName == null ? null : loginName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.login_pwd
     *
     * @return the value of user.login_pwd
     *
     * @mbg.generated
     */
    public String getLoginPwd() {
        return loginPwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.login_pwd
     *
     * @param loginPwd the value for user.login_pwd
     *
     * @mbg.generated
     */
    public void setLoginPwd(String loginPwd) {
        this.loginPwd = loginPwd == null ? null : loginPwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_name
     *
     * @return the value of user.user_name
     *
     * @mbg.generated
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_name
     *
     * @param userName the value for user.user_name
     *
     * @mbg.generated
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.sex
     *
     * @return the value of user.sex
     *
     * @mbg.generated
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.sex
     *
     * @param sex the value for user.sex
     *
     * @mbg.generated
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.mobile
     *
     * @return the value of user.mobile
     *
     * @mbg.generated
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.mobile
     *
     * @param mobile the value for user.mobile
     *
     * @mbg.generated
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.is_mobile_valid
     *
     * @return the value of user.is_mobile_valid
     *
     * @mbg.generated
     */
    public Boolean getIsMobileValid() {
        return isMobileValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.is_mobile_valid
     *
     * @param isMobileValid the value for user.is_mobile_valid
     *
     * @mbg.generated
     */
    public void setIsMobileValid(Boolean isMobileValid) {
        this.isMobileValid = isMobileValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.email
     *
     * @return the value of user.email
     *
     * @mbg.generated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.email
     *
     * @param email the value for user.email
     *
     * @mbg.generated
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.is_email_valid
     *
     * @return the value of user.is_email_valid
     *
     * @mbg.generated
     */
    public Boolean getIsEmailValid() {
        return isEmailValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.is_email_valid
     *
     * @param isEmailValid the value for user.is_email_valid
     *
     * @mbg.generated
     */
    public void setIsEmailValid(Boolean isEmailValid) {
        this.isEmailValid = isEmailValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.create_time
     *
     * @return the value of user.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.create_time
     *
     * @param createTime the value for user.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.STATUS
     *
     * @return the value of user.STATUS
     *
     * @mbg.generated
     */
    public Boolean getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.STATUS
     *
     * @param status the value for user.STATUS
     *
     * @mbg.generated
     */
    public void setStatus(Boolean status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.qq
     *
     * @return the value of user.qq
     *
     * @mbg.generated
     */
    public String getQq() {
        return qq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.qq
     *
     * @param qq the value for user.qq
     *
     * @mbg.generated
     */
    public void setQq(String qq) {
        this.qq = qq == null ? null : qq.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.last_login_time
     *
     * @return the value of user.last_login_time
     *
     * @mbg.generated
     */
    public Date getLastLoginTime() {
        return lastLoginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.last_login_time
     *
     * @param lastLoginTime the value for user.last_login_time
     *
     * @mbg.generated
     */
    public void setLastLoginTime(Date lastLoginTime) {
        this.lastLoginTime = lastLoginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.weixin_id
     *
     * @return the value of user.weixin_id
     *
     * @mbg.generated
     */
    public String getWeixinId() {
        return weixinId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.weixin_id
     *
     * @param weixinId the value for user.weixin_id
     *
     * @mbg.generated
     */
    public void setWeixinId(String weixinId) {
        this.weixinId = weixinId == null ? null : weixinId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.job
     *
     * @return the value of user.job
     *
     * @mbg.generated
     */
    public String getJob() {
        return job;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.job
     *
     * @param job the value for user.job
     *
     * @mbg.generated
     */
    public void setJob(String job) {
        this.job = job == null ? null : job.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.head_name
     *
     * @return the value of user.head_name
     *
     * @mbg.generated
     */
    public String getHeadName() {
        return headName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.head_name
     *
     * @param headName the value for user.head_name
     *
     * @mbg.generated
     */
    public void setHeadName(String headName) {
        this.headName = headName == null ? null : headName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.birthday
     *
     * @return the value of user.birthday
     *
     * @mbg.generated
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.birthday
     *
     * @param birthday the value for user.birthday
     *
     * @mbg.generated
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.upper_Id
     *
     * @return the value of user.upper_Id
     *
     * @mbg.generated
     */
    public Integer getUpperId() {
        return upperId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.upper_Id
     *
     * @param upperId the value for user.upper_Id
     *
     * @mbg.generated
     */
    public void setUpperId(Integer upperId) {
        this.upperId = upperId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.pass_code
     *
     * @return the value of user.pass_code
     *
     * @mbg.generated
     */
    public Integer getPassCode() {
        return passCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.pass_code
     *
     * @param passCode the value for user.pass_code
     *
     * @mbg.generated
     */
    public void setPassCode(Integer passCode) {
        this.passCode = passCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.is_admin
     *
     * @return the value of user.is_admin
     *
     * @mbg.generated
     */
    public Boolean getIsAdmin() {
        return isAdmin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.is_admin
     *
     * @param isAdmin the value for user.is_admin
     *
     * @mbg.generated
     */
    public void setIsAdmin(Boolean isAdmin) {
        this.isAdmin = isAdmin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.is_agree_disclaimer
     *
     * @return the value of user.is_agree_disclaimer
     *
     * @mbg.generated
     */
    public Boolean getIsAgreeDisclaimer() {
        return isAgreeDisclaimer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.is_agree_disclaimer
     *
     * @param isAgreeDisclaimer the value for user.is_agree_disclaimer
     *
     * @mbg.generated
     */
    public void setIsAgreeDisclaimer(Boolean isAgreeDisclaimer) {
        this.isAgreeDisclaimer = isAgreeDisclaimer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.agree_disclaimer_time
     *
     * @return the value of user.agree_disclaimer_time
     *
     * @mbg.generated
     */
    public Date getAgreeDisclaimerTime() {
        return agreeDisclaimerTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.agree_disclaimer_time
     *
     * @param agreeDisclaimerTime the value for user.agree_disclaimer_time
     *
     * @mbg.generated
     */
    public void setAgreeDisclaimerTime(Date agreeDisclaimerTime) {
        this.agreeDisclaimerTime = agreeDisclaimerTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.pwd_update_time
     *
     * @return the value of user.pwd_update_time
     *
     * @mbg.generated
     */
    public Date getPwdUpdateTime() {
        return pwdUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.pwd_update_time
     *
     * @param pwdUpdateTime the value for user.pwd_update_time
     *
     * @mbg.generated
     */
    public void setPwdUpdateTime(Date pwdUpdateTime) {
        this.pwdUpdateTime = pwdUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", companyId=").append(companyId);
        sb.append(", loginName=").append(loginName);
        sb.append(", loginPwd=").append(loginPwd);
        sb.append(", userName=").append(userName);
        sb.append(", sex=").append(sex);
        sb.append(", mobile=").append(mobile);
        sb.append(", isMobileValid=").append(isMobileValid);
        sb.append(", email=").append(email);
        sb.append(", isEmailValid=").append(isEmailValid);
        sb.append(", createTime=").append(createTime);
        sb.append(", status=").append(status);
        sb.append(", qq=").append(qq);
        sb.append(", lastLoginTime=").append(lastLoginTime);
        sb.append(", weixinId=").append(weixinId);
        sb.append(", job=").append(job);
        sb.append(", headName=").append(headName);
        sb.append(", birthday=").append(birthday);
        sb.append(", upperId=").append(upperId);
        sb.append(", passCode=").append(passCode);
        sb.append(", isAdmin=").append(isAdmin);
        sb.append(", isAgreeDisclaimer=").append(isAgreeDisclaimer);
        sb.append(", agreeDisclaimerTime=").append(agreeDisclaimerTime);
        sb.append(", pwdUpdateTime=").append(pwdUpdateTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}